/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import type { AccessControlControllerCreateRoleV1201RolePermissionsItemPermission } from './accessControlControllerCreateRoleV1201RolePermissionsItemPermission';

export type AccessControlControllerCreateRoleV1201RolePermissionsItem = {
  permission?: AccessControlControllerCreateRoleV1201RolePermissionsItemPermission;
};
