/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */

export type AccessControlControllerGetMemberPermissionBreakdownV1200 = {
  /** Permission IDs inherited from the member's assigned role */
  rolePermissionIds?: string[];
  /** Permission IDs granted as explicit overrides */
  grantedOverrideIds?: string[];
};
