/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import type { AccessControlControllerGetRolesV1200ItemRolePermissionsItem } from './accessControlControllerGetRolesV1200ItemRolePermissionsItem';

export type AccessControlControllerGetRolesV1200Item = {
  id?: string;
  name?: string;
  organization_id?: string;
  created_at?: string;
  rolePermissions?: AccessControlControllerGetRolesV1200ItemRolePermissionsItem[];
};
