/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import type { AccessControlControllerUpdateRoleV1200RolePermissionsItem } from './accessControlControllerUpdateRoleV1200RolePermissionsItem';

export type AccessControlControllerUpdateRoleV1200 = {
  id?: string;
  name?: string;
  organization_id?: string;
  created_at?: string;
  rolePermissions?: AccessControlControllerUpdateRoleV1200RolePermissionsItem[];
};
