/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import type { AccessControlControllerCreateRoleV1201RolePermissionsItem } from './accessControlControllerCreateRoleV1201RolePermissionsItem';

export type AccessControlControllerCreateRoleV1201 = {
  id?: string;
  name?: string;
  organization_id?: string;
  created_at?: string;
  rolePermissions?: AccessControlControllerCreateRoleV1201RolePermissionsItem[];
};
