/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import type { AccessControlControllerUpdateRoleV1200RolePermissionsItemPermission } from './accessControlControllerUpdateRoleV1200RolePermissionsItemPermission';

export type AccessControlControllerUpdateRoleV1200RolePermissionsItem = {
  permission?: AccessControlControllerUpdateRoleV1200RolePermissionsItemPermission;
};
