/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import type { AccessControlControllerGetRolesV1200ItemRolePermissionsItemPermission } from './accessControlControllerGetRolesV1200ItemRolePermissionsItemPermission';

export type AccessControlControllerGetRolesV1200ItemRolePermissionsItem = {
  permission?: AccessControlControllerGetRolesV1200ItemRolePermissionsItemPermission;
};
