/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */

export type AnalyticsControllerGetDashboardMetricsV1Params = {
  /**
   * Optionally scope dashboard metrics to a specific assigned agent
   */
  agent_id?: string;
};
