/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import type { BulkUpdateLeadDataDtoStatus } from './bulkUpdateLeadDataDtoStatus';
import type { BulkUpdateLeadDataDtoPriority } from './bulkUpdateLeadDataDtoPriority';
import type { BulkUpdateLeadDataDtoAssignedAgentId } from './bulkUpdateLeadDataDtoAssignedAgentId';

export interface BulkUpdateLeadDataDto {
  status?: BulkUpdateLeadDataDtoStatus;
  priority?: BulkUpdateLeadDataDtoPriority;
  /** @nullable */
  assigned_agent_id?: BulkUpdateLeadDataDtoAssignedAgentId;
}
