/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import type { CreateLeadDto } from './createLeadDto';

export interface BulkCreateLeadsDto {
  /**
   * Array of leads to create (max 500 items per request)
   * @minItems 1
   * @maxItems 500
   */
  leads: CreateLeadDto[];
}
