/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import type { CreateLeadDtoNativeName } from './createLeadDtoNativeName';
import type { CreateLeadDtoGender } from './createLeadDtoGender';
import type { CreateLeadDtoEmail } from './createLeadDtoEmail';
import type { CreateLeadDtoPreferredLanguage } from './createLeadDtoPreferredLanguage';
import type { CreateLeadDtoSocialLinks } from './createLeadDtoSocialLinks';
import type { CreateLeadDtoStatus } from './createLeadDtoStatus';
import type { CreateLeadDtoPriority } from './createLeadDtoPriority';
import type { CreateLeadDtoEstimatedValue } from './createLeadDtoEstimatedValue';
import type { CreateLeadDtoCurrency } from './createLeadDtoCurrency';
import type { CreateLeadDtoExpectedServiceDate } from './createLeadDtoExpectedServiceDate';
import type { CreateLeadDtoNextFollowUpAt } from './createLeadDtoNextFollowUpAt';
import type { CreateLeadDtoAssignedAgentId } from './createLeadDtoAssignedAgentId';
import type { CreateLeadDtoSourceId } from './createLeadDtoSourceId';

export interface CreateLeadDto {
  first_name: string;
  last_name: string;
  phone_number: string;
  country: string;
  timezone: string;
  primary_language: string;
  /** @nullable */
  native_name?: CreateLeadDtoNativeName;
  gender?: CreateLeadDtoGender;
  /** @nullable */
  email?: CreateLeadDtoEmail;
  /** @nullable */
  preferred_language?: CreateLeadDtoPreferredLanguage;
  /** @nullable */
  social_links?: CreateLeadDtoSocialLinks;
  status?: CreateLeadDtoStatus;
  priority?: CreateLeadDtoPriority;
  /**
   * Decimal value represented as string to preserve precision
   * @nullable
   */
  estimated_value?: CreateLeadDtoEstimatedValue;
  currency?: CreateLeadDtoCurrency;
  /** @nullable */
  expected_service_date?: CreateLeadDtoExpectedServiceDate;
  /** @nullable */
  next_follow_up_at?: CreateLeadDtoNextFollowUpAt;
  /** @nullable */
  assigned_agent_id?: CreateLeadDtoAssignedAgentId;
  /** @nullable */
  source_id?: CreateLeadDtoSourceId;
}
