/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */

export type CreateLeadDtoGender =
  (typeof CreateLeadDtoGender)[keyof typeof CreateLeadDtoGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateLeadDtoGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  OTHER: 'OTHER',
  UNKNOWN: 'UNKNOWN',
} as const;
