/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */

export type CreateLeadDtoCurrency =
  (typeof CreateLeadDtoCurrency)[keyof typeof CreateLeadDtoCurrency];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateLeadDtoCurrency = {
  USD: 'USD',
  TRY: 'TRY',
  EUR: 'EUR',
  GBP: 'GBP',
} as const;
