/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */

/**
 * Translations of the role name (optional)
 */
export type CreateRoleDtoNameTranslations = { [key: string]: unknown };
