/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */

export type CreateLeadDtoStatus =
  (typeof CreateLeadDtoStatus)[keyof typeof CreateLeadDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateLeadDtoStatus = {
  OPEN: 'OPEN',
  WON: 'WON',
  LOST: 'LOST',
  UNQUALIFIED: 'UNQUALIFIED',
} as const;
