/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */

/**
 * Decimal value represented as string to preserve precision
 * @nullable
 */
export type CreateLeadDtoEstimatedValue = { [key: string]: unknown } | null;
