/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */

export interface CreatePermissionOverrideDto {
  /** The permission ID to override */
  permission_id: string;
  /** Whether to grant (true) or revoke (false) this permission */
  is_granted: boolean;
}
