/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */

export interface InviteToOrganizationDto {
  /** The email address of the user to invite */
  email: string;
  /** The role ID to assign when the invite is accepted */
  roleId: string;
}
