/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */

export type LeadsControllerFindAllV1Priority =
  (typeof LeadsControllerFindAllV1Priority)[keyof typeof LeadsControllerFindAllV1Priority];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LeadsControllerFindAllV1Priority = {
  HOT: 'HOT',
  WARM: 'WARM',
  COLD: 'COLD',
} as const;
