/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import type { LeadsControllerFindAllV1Status } from './leadsControllerFindAllV1Status';
import type { LeadsControllerFindAllV1Priority } from './leadsControllerFindAllV1Priority';

export type LeadsControllerFindAllV1Params = {
  page?: number;
  /**
   * @maximum 100
   */
  limit?: number;
  /**
   * A JSON-stringified AST for filtering with AND/OR logic and dynamic operators.
   */
  filters?: string;
  /**
   * A JSON-stringified array of sort nodes.
   */
  sorts?: string;
  status?: LeadsControllerFindAllV1Status;
  priority?: LeadsControllerFindAllV1Priority;
};
