/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import type { LeadsControllerExportAllV1Status } from './leadsControllerExportAllV1Status';
import type { LeadsControllerExportAllV1Priority } from './leadsControllerExportAllV1Priority';

export type LeadsControllerExportAllV1Params = {
  page?: number;
  /**
   * @maximum 100
   */
  limit?: number;
  /**
   * A JSON-stringified AST for filtering with AND/OR logic and dynamic operators.
   */
  filters?: string;
  /**
   * A JSON-stringified array of sort nodes.
   */
  sorts?: string;
  status?: LeadsControllerExportAllV1Status;
  priority?: LeadsControllerExportAllV1Priority;
};
