/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */

export type MembershipAccessControlControllerCreatePermissionOverrideV1201 = {
  id?: string;
  permission_id?: string;
  is_granted?: boolean;
  message?: string;
};
