/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */

export type OrganizationsControllerCreateV1201 = {
  id?: string;
  name?: string;
  slug?: string;
  is_public?: boolean;
  created_at?: string;
};
