/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import type { OrganizationsControllerListPendingInvitationsV1200ItemRole } from './organizationsControllerListPendingInvitationsV1200ItemRole';

export type OrganizationsControllerListPendingInvitationsV1200Item = {
  id?: string;
  token?: string;
  email?: string;
  status?: string;
  created_at?: string;
  inviteUrl?: string;
  role?: OrganizationsControllerListPendingInvitationsV1200ItemRole;
};
