/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */

export type OrganizationsControllerGetMembersV1200ItemStatus =
  (typeof OrganizationsControllerGetMembersV1200ItemStatus)[keyof typeof OrganizationsControllerGetMembersV1200ItemStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrganizationsControllerGetMembersV1200ItemStatus = {
  ACTIVE: 'ACTIVE',
} as const;
