/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import type { OrganizationsControllerGetMembersV1200ItemUser } from './organizationsControllerGetMembersV1200ItemUser';
import type { OrganizationsControllerGetMembersV1200ItemRole } from './organizationsControllerGetMembersV1200ItemRole';
import type { OrganizationsControllerGetMembersV1200ItemStatus } from './organizationsControllerGetMembersV1200ItemStatus';

export type OrganizationsControllerGetMembersV1200Item = {
  membershipId?: string;
  organizationId?: string;
  user?: OrganizationsControllerGetMembersV1200ItemUser;
  role?: OrganizationsControllerGetMembersV1200ItemRole;
  status?: OrganizationsControllerGetMembersV1200ItemStatus;
};
