/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */

export type OrganizationsControllerGetInvitationByTokenV1200 = {
  organizationName?: string;
  roleName?: string;
  email?: string;
  status?: string;
};
