/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */

export type ProductsControllerFindAllV1Type =
  (typeof ProductsControllerFindAllV1Type)[keyof typeof ProductsControllerFindAllV1Type];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductsControllerFindAllV1Type = {
  REAL_ESTATE_ASSET: 'REAL_ESTATE_ASSET',
  SCHEDULED_EVENT: 'SCHEDULED_EVENT',
  RESOURCE_RENTAL: 'RESOURCE_RENTAL',
  DYNAMIC_SERVICE: 'DYNAMIC_SERVICE',
} as const;
