/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */

export type ProposalsControllerFindAllV1Status =
  (typeof ProposalsControllerFindAllV1Status)[keyof typeof ProposalsControllerFindAllV1Status];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProposalsControllerFindAllV1Status = {
  DRAFT: 'DRAFT',
  SENT: 'SENT',
  ACCEPTED: 'ACCEPTED',
  RECEIPT_UPLOADED: 'RECEIPT_UPLOADED',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
  EXPIRED: 'EXPIRED',
} as const;
