/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import type { ProposalsControllerFindAllV1Status } from './proposalsControllerFindAllV1Status';

export type ProposalsControllerFindAllV1Params = {
  page?: number;
  /**
   * @maximum 100
   */
  limit?: number;
  /**
   * A JSON-stringified AST for filtering with AND/OR logic and dynamic operators.
   */
  filters?: string;
  /**
   * A JSON-stringified array of sort nodes.
   */
  sorts?: string;
  status?: ProposalsControllerFindAllV1Status;
};
