/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */

export interface RegisterDto {
  email: string;
  password: string;
  first_name: string;
  last_name: string;
  inviteToken?: string;
}
