/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */

export type UpdateLeadDtoPriority =
  (typeof UpdateLeadDtoPriority)[keyof typeof UpdateLeadDtoPriority];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateLeadDtoPriority = {
  HOT: 'HOT',
  WARM: 'WARM',
  COLD: 'COLD',
} as const;
