/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */

export interface UpdateUserProfileDto {
  /** URL to user avatar image */
  avatar_url?: string;
  /** Phone number of the user */
  phone_number?: string;
  /** WhatsApp number of the user */
  whatsapp_number?: string;
  spoken_languages?: unknown[][];
}
