/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */

export interface UpdateAiPersonaDto {
  /** Organization UUID - cannot be updated */
  organizationId?: string;
  /**
   * System prompt for the AI persona
   * @minLength 10
   */
  systemPrompt?: string;
  /** Display name for the AI persona */
  name?: string;
  /** Voice ID for text-to-speech (ElevenLabs or OpenAI) */
  voiceId?: string;
  /** Whether the AI persona can negotiate */
  canNegotiate?: boolean;
  /** Automatically attend to new leads */
  autoAttendNewLeads?: boolean;
  /** Speed of outbound messages (0-100) */
  outboundMessagesSpeed?: number;
  /** Sleep start time (HH:MM format) */
  sleepStartHour?: string;
  /** Sleep end time (HH:MM format) */
  sleepEndHour?: string;
}
