/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */

/**
 * Agent tier/level in the organization
 */
export type UpdateMemberProfileDtoAgentTier =
  (typeof UpdateMemberProfileDtoAgentTier)[keyof typeof UpdateMemberProfileDtoAgentTier];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateMemberProfileDtoAgentTier = {
  JUNIOR: 'JUNIOR',
  STANDARD: 'STANDARD',
  SENIOR: 'SENIOR',
  MANAGER: 'MANAGER',
} as const;
