/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */

/**
 * Availability status of the member
 */
export type UpdateMemberProfileDtoAvailabilityStatus =
  (typeof UpdateMemberProfileDtoAvailabilityStatus)[keyof typeof UpdateMemberProfileDtoAvailabilityStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateMemberProfileDtoAvailabilityStatus = {
  ACTIVE: 'ACTIVE',
  ON_LEAVE: 'ON_LEAVE',
  OFF_SHIFT: 'OFF_SHIFT',
} as const;
