/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import type { UpdateMemberProfileDtoAgentTier } from './updateMemberProfileDtoAgentTier';
import type { UpdateMemberProfileDtoAvailabilityStatus } from './updateMemberProfileDtoAvailabilityStatus';

export interface UpdateMemberProfileDto {
  /** Job title of the member in the organization */
  job_title?: string;
  /** Agent tier/level in the organization */
  agent_tier?: UpdateMemberProfileDtoAgentTier;
  specializations?: unknown[][];
  /** Availability status of the member */
  availability_status?: UpdateMemberProfileDtoAvailabilityStatus;
  /**
   * Maximum number of active leads this member can handle
   * @minimum 1
   */
  max_active_leads?: number;
  /**
   * Commission rate as a percentage (0-100)
   * @minimum 0
   * @maximum 100
   */
  commission_rate?: number;
  /**
   * Monthly revenue target for this member
   * @minimum 0
   */
  monthly_revenue_target?: number;
}
