/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */

export interface UpdateMemberRoleDto {
  /** The role ID to assign to this membership */
  role_id: string;
}
