/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import type { UpdateLeadDtoNativeName } from './updateLeadDtoNativeName';
import type { UpdateLeadDtoGender } from './updateLeadDtoGender';
import type { UpdateLeadDtoEmail } from './updateLeadDtoEmail';
import type { UpdateLeadDtoPreferredLanguage } from './updateLeadDtoPreferredLanguage';
import type { UpdateLeadDtoSocialLinks } from './updateLeadDtoSocialLinks';
import type { UpdateLeadDtoStatus } from './updateLeadDtoStatus';
import type { UpdateLeadDtoPriority } from './updateLeadDtoPriority';
import type { UpdateLeadDtoEstimatedValue } from './updateLeadDtoEstimatedValue';
import type { UpdateLeadDtoCurrency } from './updateLeadDtoCurrency';
import type { UpdateLeadDtoExpectedServiceDate } from './updateLeadDtoExpectedServiceDate';
import type { UpdateLeadDtoNextFollowUpAt } from './updateLeadDtoNextFollowUpAt';
import type { UpdateLeadDtoPipelineStageId } from './updateLeadDtoPipelineStageId';
import type { UpdateLeadDtoAssignedAgentId } from './updateLeadDtoAssignedAgentId';
import type { UpdateLeadDtoSourceId } from './updateLeadDtoSourceId';

export interface UpdateLeadDto {
  first_name?: string;
  last_name?: string;
  phone_number?: string;
  country?: string;
  timezone?: string;
  primary_language?: string;
  /** @nullable */
  native_name?: UpdateLeadDtoNativeName;
  gender?: UpdateLeadDtoGender;
  /** @nullable */
  email?: UpdateLeadDtoEmail;
  /** @nullable */
  preferred_language?: UpdateLeadDtoPreferredLanguage;
  /** @nullable */
  social_links?: UpdateLeadDtoSocialLinks;
  status?: UpdateLeadDtoStatus;
  priority?: UpdateLeadDtoPriority;
  /**
   * Decimal value represented as string to preserve precision
   * @nullable
   */
  estimated_value?: UpdateLeadDtoEstimatedValue;
  currency?: UpdateLeadDtoCurrency;
  /** @nullable */
  expected_service_date?: UpdateLeadDtoExpectedServiceDate;
  /** @nullable */
  next_follow_up_at?: UpdateLeadDtoNextFollowUpAt;
  /** @nullable */
  pipeline_stage_id?: UpdateLeadDtoPipelineStageId;
  /** @nullable */
  assigned_agent_id?: UpdateLeadDtoAssignedAgentId;
  /** @nullable */
  source_id?: UpdateLeadDtoSourceId;
}
