/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import type { UpdateOrganizationDtoBrandColors } from './updateOrganizationDtoBrandColors';

export interface UpdateOrganizationDto {
  /** The name of the organization */
  name?: string;
  /** Whether the organization is publicly visible */
  is_public?: boolean;
  /** Tax identification number */
  tax_number?: string;
  /** Tax office location */
  tax_office?: string;
  /** URL to organization logo */
  logo_url?: string;
  /** Brand colors (hex values) */
  brand_colors?: UpdateOrganizationDtoBrandColors;
  /** Default currency for organization */
  default_currency?: string;
  /** Industry category */
  industry_category?: string;
  /** Physical address of organization */
  address?: string;
  /** Organization website URL */
  website_url?: string;
  /** Public email address */
  public_email?: string;
  /** Public phone number */
  public_phone?: string;
  /** Terms and conditions */
  terms_and_conditions?: string;
  /** Privacy policy */
  privacy_policy?: string;
}
