/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */

export type UsersControllerGetUserOrganizationsV1200ItemStatus =
  (typeof UsersControllerGetUserOrganizationsV1200ItemStatus)[keyof typeof UsersControllerGetUserOrganizationsV1200ItemStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersControllerGetUserOrganizationsV1200ItemStatus = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  REJECTED: 'REJECTED',
} as const;
