/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */

export type UsersControllerGetCurrentUserV1200 = {
  id?: string;
  email?: string;
  first_name?: string;
  last_name?: string;
  created_at?: string;
  /** User permissions for the specified organization */
  permissions?: string[];
};
