/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */

export type UsersControllerGetPerformanceProfileV1200Metrics = {
  closed_revenue_mtd?: number;
  active_pipeline_value?: number;
};
