/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import type { UsersControllerGetUserOrganizationsV1200ItemStatus } from './usersControllerGetUserOrganizationsV1200ItemStatus';
import type { UsersControllerGetUserOrganizationsV1200ItemOrganization } from './usersControllerGetUserOrganizationsV1200ItemOrganization';
import type { UsersControllerGetUserOrganizationsV1200ItemRole } from './usersControllerGetUserOrganizationsV1200ItemRole';

export type UsersControllerGetUserOrganizationsV1200Item = {
  membership_id?: string;
  organization_id?: string;
  role_id?: string;
  status?: UsersControllerGetUserOrganizationsV1200ItemStatus;
  created_at?: string;
  organization?: UsersControllerGetUserOrganizationsV1200ItemOrganization;
  role?: UsersControllerGetUserOrganizationsV1200ItemRole;
};
