/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */

export type UsersControllerAcceptInviteV1200 = {
  message?: string;
  membership_id?: string;
  organization_name?: string;
  role?: string;
};
