/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import type { UsersControllerGetPerformanceProfileV1200User } from './usersControllerGetPerformanceProfileV1200User';
import type { UsersControllerGetPerformanceProfileV1200Membership } from './usersControllerGetPerformanceProfileV1200Membership';
import type { UsersControllerGetPerformanceProfileV1200Metrics } from './usersControllerGetPerformanceProfileV1200Metrics';

export type UsersControllerGetPerformanceProfileV1200 = {
  user?: UsersControllerGetPerformanceProfileV1200User;
  membership?: UsersControllerGetPerformanceProfileV1200Membership;
  metrics?: UsersControllerGetPerformanceProfileV1200Metrics;
};
