/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { CreateAiPersonaDto, UpdateAiPersonaDto } from '../model';

import { customInstance } from '../../lib/api-custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Create an AI Persona for an organization
 */
export const aiPersonasControllerCreateV1 = (
  createAiPersonaDto: CreateAiPersonaDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/ai-personas`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createAiPersonaDto,
      signal,
    },
    options
  );
};

export const getAiPersonasControllerCreateV1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aiPersonasControllerCreateV1>>,
    TError,
    { data: CreateAiPersonaDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof aiPersonasControllerCreateV1>>,
  TError,
  { data: CreateAiPersonaDto },
  TContext
> => {
  const mutationKey = ['aiPersonasControllerCreateV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof aiPersonasControllerCreateV1>>,
    { data: CreateAiPersonaDto }
  > = (props) => {
    const { data } = props ?? {};

    return aiPersonasControllerCreateV1(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AiPersonasControllerCreateV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof aiPersonasControllerCreateV1>>
>;
export type AiPersonasControllerCreateV1MutationBody = CreateAiPersonaDto;
export type AiPersonasControllerCreateV1MutationError = unknown;

/**
 * @summary Create an AI Persona for an organization
 */
export const useAiPersonasControllerCreateV1 = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof aiPersonasControllerCreateV1>>,
      TError,
      { data: CreateAiPersonaDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof aiPersonasControllerCreateV1>>,
  TError,
  { data: CreateAiPersonaDto },
  TContext
> => {
  const mutationOptions =
    getAiPersonasControllerCreateV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get AI Persona for a specific organization
 */
export const aiPersonasControllerFindByOrganizationV1 = (
  organizationId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    { url: `/api/v1/ai-personas/org/${organizationId}`, method: 'GET', signal },
    options
  );
};

export const getAiPersonasControllerFindByOrganizationV1QueryKey = (
  organizationId?: string
) => {
  return [`/api/v1/ai-personas/org/${organizationId}`] as const;
};

export const getAiPersonasControllerFindByOrganizationV1QueryOptions = <
  TData = Awaited<ReturnType<typeof aiPersonasControllerFindByOrganizationV1>>,
  TError = void,
>(
  organizationId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof aiPersonasControllerFindByOrganizationV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getAiPersonasControllerFindByOrganizationV1QueryKey(organizationId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof aiPersonasControllerFindByOrganizationV1>>
  > = ({ signal }) =>
    aiPersonasControllerFindByOrganizationV1(
      organizationId,
      requestOptions,
      signal
    );

  return {
    queryKey,
    queryFn,
    enabled: !!organizationId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof aiPersonasControllerFindByOrganizationV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AiPersonasControllerFindByOrganizationV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof aiPersonasControllerFindByOrganizationV1>>
>;
export type AiPersonasControllerFindByOrganizationV1QueryError = void;

export function useAiPersonasControllerFindByOrganizationV1<
  TData = Awaited<ReturnType<typeof aiPersonasControllerFindByOrganizationV1>>,
  TError = void,
>(
  organizationId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof aiPersonasControllerFindByOrganizationV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof aiPersonasControllerFindByOrganizationV1>>,
          TError,
          Awaited<ReturnType<typeof aiPersonasControllerFindByOrganizationV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAiPersonasControllerFindByOrganizationV1<
  TData = Awaited<ReturnType<typeof aiPersonasControllerFindByOrganizationV1>>,
  TError = void,
>(
  organizationId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof aiPersonasControllerFindByOrganizationV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof aiPersonasControllerFindByOrganizationV1>>,
          TError,
          Awaited<ReturnType<typeof aiPersonasControllerFindByOrganizationV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAiPersonasControllerFindByOrganizationV1<
  TData = Awaited<ReturnType<typeof aiPersonasControllerFindByOrganizationV1>>,
  TError = void,
>(
  organizationId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof aiPersonasControllerFindByOrganizationV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get AI Persona for a specific organization
 */

export function useAiPersonasControllerFindByOrganizationV1<
  TData = Awaited<ReturnType<typeof aiPersonasControllerFindByOrganizationV1>>,
  TError = void,
>(
  organizationId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof aiPersonasControllerFindByOrganizationV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAiPersonasControllerFindByOrganizationV1QueryOptions(
    organizationId,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update an AI Persona
 */
export const aiPersonasControllerUpdateV1 = (
  id: string,
  updateAiPersonaDto: UpdateAiPersonaDto,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    {
      url: `/api/v1/ai-personas/${id}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateAiPersonaDto,
    },
    options
  );
};

export const getAiPersonasControllerUpdateV1MutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aiPersonasControllerUpdateV1>>,
    TError,
    { id: string; data: UpdateAiPersonaDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof aiPersonasControllerUpdateV1>>,
  TError,
  { id: string; data: UpdateAiPersonaDto },
  TContext
> => {
  const mutationKey = ['aiPersonasControllerUpdateV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof aiPersonasControllerUpdateV1>>,
    { id: string; data: UpdateAiPersonaDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return aiPersonasControllerUpdateV1(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AiPersonasControllerUpdateV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof aiPersonasControllerUpdateV1>>
>;
export type AiPersonasControllerUpdateV1MutationBody = UpdateAiPersonaDto;
export type AiPersonasControllerUpdateV1MutationError = void;

/**
 * @summary Update an AI Persona
 */
export const useAiPersonasControllerUpdateV1 = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof aiPersonasControllerUpdateV1>>,
      TError,
      { id: string; data: UpdateAiPersonaDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof aiPersonasControllerUpdateV1>>,
  TError,
  { id: string; data: UpdateAiPersonaDto },
  TContext
> => {
  const mutationOptions =
    getAiPersonasControllerUpdateV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Delete an AI Persona
 */
export const aiPersonasControllerRemoveV1 = (
  id: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    { url: `/api/v1/ai-personas/${id}`, method: 'DELETE' },
    options
  );
};

export const getAiPersonasControllerRemoveV1MutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aiPersonasControllerRemoveV1>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof aiPersonasControllerRemoveV1>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['aiPersonasControllerRemoveV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof aiPersonasControllerRemoveV1>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return aiPersonasControllerRemoveV1(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AiPersonasControllerRemoveV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof aiPersonasControllerRemoveV1>>
>;

export type AiPersonasControllerRemoveV1MutationError = void;

/**
 * @summary Delete an AI Persona
 */
export const useAiPersonasControllerRemoveV1 = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof aiPersonasControllerRemoveV1>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof aiPersonasControllerRemoveV1>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions =
    getAiPersonasControllerRemoveV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
