/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { AnalyticsControllerGetDashboardMetricsV1Params } from '../model';

import { customInstance } from '../../lib/api-custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Get dashboard analytics metrics
 */
export const analyticsControllerGetDashboardMetricsV1 = (
  organizationId: string,
  params?: AnalyticsControllerGetDashboardMetricsV1Params,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/analytics/dashboard`,
      method: 'GET',
      params,
      signal,
    },
    options
  );
};

export const getAnalyticsControllerGetDashboardMetricsV1QueryKey = (
  organizationId?: string,
  params?: AnalyticsControllerGetDashboardMetricsV1Params
) => {
  return [
    `/api/v1/organizations/${organizationId}/analytics/dashboard`,
    ...(params ? [params] : []),
  ] as const;
};

export const getAnalyticsControllerGetDashboardMetricsV1QueryOptions = <
  TData = Awaited<ReturnType<typeof analyticsControllerGetDashboardMetricsV1>>,
  TError = unknown,
>(
  organizationId: string,
  params?: AnalyticsControllerGetDashboardMetricsV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof analyticsControllerGetDashboardMetricsV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getAnalyticsControllerGetDashboardMetricsV1QueryKey(organizationId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof analyticsControllerGetDashboardMetricsV1>>
  > = ({ signal }) =>
    analyticsControllerGetDashboardMetricsV1(
      organizationId,
      params,
      requestOptions,
      signal
    );

  return {
    queryKey,
    queryFn,
    enabled: !!organizationId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof analyticsControllerGetDashboardMetricsV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AnalyticsControllerGetDashboardMetricsV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof analyticsControllerGetDashboardMetricsV1>>
>;
export type AnalyticsControllerGetDashboardMetricsV1QueryError = unknown;

export function useAnalyticsControllerGetDashboardMetricsV1<
  TData = Awaited<ReturnType<typeof analyticsControllerGetDashboardMetricsV1>>,
  TError = unknown,
>(
  organizationId: string,
  params: undefined | AnalyticsControllerGetDashboardMetricsV1Params,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof analyticsControllerGetDashboardMetricsV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof analyticsControllerGetDashboardMetricsV1>>,
          TError,
          Awaited<ReturnType<typeof analyticsControllerGetDashboardMetricsV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAnalyticsControllerGetDashboardMetricsV1<
  TData = Awaited<ReturnType<typeof analyticsControllerGetDashboardMetricsV1>>,
  TError = unknown,
>(
  organizationId: string,
  params?: AnalyticsControllerGetDashboardMetricsV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof analyticsControllerGetDashboardMetricsV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof analyticsControllerGetDashboardMetricsV1>>,
          TError,
          Awaited<ReturnType<typeof analyticsControllerGetDashboardMetricsV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAnalyticsControllerGetDashboardMetricsV1<
  TData = Awaited<ReturnType<typeof analyticsControllerGetDashboardMetricsV1>>,
  TError = unknown,
>(
  organizationId: string,
  params?: AnalyticsControllerGetDashboardMetricsV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof analyticsControllerGetDashboardMetricsV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get dashboard analytics metrics
 */

export function useAnalyticsControllerGetDashboardMetricsV1<
  TData = Awaited<ReturnType<typeof analyticsControllerGetDashboardMetricsV1>>,
  TError = unknown,
>(
  organizationId: string,
  params?: AnalyticsControllerGetDashboardMetricsV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof analyticsControllerGetDashboardMetricsV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAnalyticsControllerGetDashboardMetricsV1QueryOptions(
    organizationId,
    params,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
