/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  LoginDto,
  RegisterDto,
  RequestPasswordResetDto,
  ResendVerificationDto,
  ResetPasswordDto,
  VerifyEmailDto,
} from '../model';

import { customInstance } from '../../lib/api-custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary User login
 */
export const authControllerLoginV1 = (
  loginDto: LoginDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/auth/login`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: loginDto,
      signal,
    },
    options
  );
};

export const getAuthControllerLoginV1MutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerLoginV1>>,
    TError,
    { data: LoginDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerLoginV1>>,
  TError,
  { data: LoginDto },
  TContext
> => {
  const mutationKey = ['authControllerLoginV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerLoginV1>>,
    { data: LoginDto }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerLoginV1(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerLoginV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerLoginV1>>
>;
export type AuthControllerLoginV1MutationBody = LoginDto;
export type AuthControllerLoginV1MutationError = void;

/**
 * @summary User login
 */
export const useAuthControllerLoginV1 = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerLoginV1>>,
      TError,
      { data: LoginDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerLoginV1>>,
  TError,
  { data: LoginDto },
  TContext
> => {
  const mutationOptions = getAuthControllerLoginV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Verify email using one-time token
 */
export const authControllerVerifyEmailV1 = (
  verifyEmailDto: VerifyEmailDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/auth/verify-email`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: verifyEmailDto,
      signal,
    },
    options
  );
};

export const getAuthControllerVerifyEmailV1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerVerifyEmailV1>>,
    TError,
    { data: VerifyEmailDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerVerifyEmailV1>>,
  TError,
  { data: VerifyEmailDto },
  TContext
> => {
  const mutationKey = ['authControllerVerifyEmailV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerVerifyEmailV1>>,
    { data: VerifyEmailDto }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerVerifyEmailV1(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerVerifyEmailV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerVerifyEmailV1>>
>;
export type AuthControllerVerifyEmailV1MutationBody = VerifyEmailDto;
export type AuthControllerVerifyEmailV1MutationError = unknown;

/**
 * @summary Verify email using one-time token
 */
export const useAuthControllerVerifyEmailV1 = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerVerifyEmailV1>>,
      TError,
      { data: VerifyEmailDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerVerifyEmailV1>>,
  TError,
  { data: VerifyEmailDto },
  TContext
> => {
  const mutationOptions =
    getAuthControllerVerifyEmailV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Resend email verification link
 */
export const authControllerResendVerificationV1 = (
  resendVerificationDto: ResendVerificationDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/auth/resend-verification`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: resendVerificationDto,
      signal,
    },
    options
  );
};

export const getAuthControllerResendVerificationV1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerResendVerificationV1>>,
    TError,
    { data: ResendVerificationDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerResendVerificationV1>>,
  TError,
  { data: ResendVerificationDto },
  TContext
> => {
  const mutationKey = ['authControllerResendVerificationV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerResendVerificationV1>>,
    { data: ResendVerificationDto }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerResendVerificationV1(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerResendVerificationV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerResendVerificationV1>>
>;
export type AuthControllerResendVerificationV1MutationBody =
  ResendVerificationDto;
export type AuthControllerResendVerificationV1MutationError = unknown;

/**
 * @summary Resend email verification link
 */
export const useAuthControllerResendVerificationV1 = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerResendVerificationV1>>,
      TError,
      { data: ResendVerificationDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerResendVerificationV1>>,
  TError,
  { data: ResendVerificationDto },
  TContext
> => {
  const mutationOptions =
    getAuthControllerResendVerificationV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Request password reset token
 */
export const authControllerRequestPasswordResetV1 = (
  requestPasswordResetDto: RequestPasswordResetDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/auth/request-password-reset`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: requestPasswordResetDto,
      signal,
    },
    options
  );
};

export const getAuthControllerRequestPasswordResetV1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerRequestPasswordResetV1>>,
    TError,
    { data: RequestPasswordResetDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerRequestPasswordResetV1>>,
  TError,
  { data: RequestPasswordResetDto },
  TContext
> => {
  const mutationKey = ['authControllerRequestPasswordResetV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerRequestPasswordResetV1>>,
    { data: RequestPasswordResetDto }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerRequestPasswordResetV1(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerRequestPasswordResetV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerRequestPasswordResetV1>>
>;
export type AuthControllerRequestPasswordResetV1MutationBody =
  RequestPasswordResetDto;
export type AuthControllerRequestPasswordResetV1MutationError = unknown;

/**
 * @summary Request password reset token
 */
export const useAuthControllerRequestPasswordResetV1 = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerRequestPasswordResetV1>>,
      TError,
      { data: RequestPasswordResetDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerRequestPasswordResetV1>>,
  TError,
  { data: RequestPasswordResetDto },
  TContext
> => {
  const mutationOptions =
    getAuthControllerRequestPasswordResetV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Reset password using one-time token
 */
export const authControllerResetPasswordV1 = (
  resetPasswordDto: ResetPasswordDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/auth/reset-password`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: resetPasswordDto,
      signal,
    },
    options
  );
};

export const getAuthControllerResetPasswordV1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerResetPasswordV1>>,
    TError,
    { data: ResetPasswordDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerResetPasswordV1>>,
  TError,
  { data: ResetPasswordDto },
  TContext
> => {
  const mutationKey = ['authControllerResetPasswordV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerResetPasswordV1>>,
    { data: ResetPasswordDto }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerResetPasswordV1(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerResetPasswordV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerResetPasswordV1>>
>;
export type AuthControllerResetPasswordV1MutationBody = ResetPasswordDto;
export type AuthControllerResetPasswordV1MutationError = unknown;

/**
 * @summary Reset password using one-time token
 */
export const useAuthControllerResetPasswordV1 = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerResetPasswordV1>>,
      TError,
      { data: ResetPasswordDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerResetPasswordV1>>,
  TError,
  { data: ResetPasswordDto },
  TContext
> => {
  const mutationOptions =
    getAuthControllerResetPasswordV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Rotate refresh token and issue new access token
 */
export const authControllerRefreshV1 = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    { url: `/api/v1/auth/refresh`, method: 'POST', signal },
    options
  );
};

export const getAuthControllerRefreshV1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerRefreshV1>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerRefreshV1>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['authControllerRefreshV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerRefreshV1>>,
    void
  > = () => {
    return authControllerRefreshV1(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerRefreshV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerRefreshV1>>
>;

export type AuthControllerRefreshV1MutationError = unknown;

/**
 * @summary Rotate refresh token and issue new access token
 */
export const useAuthControllerRefreshV1 = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerRefreshV1>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerRefreshV1>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getAuthControllerRefreshV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Logout by revoking refresh token and clearing cookie
 */
export const authControllerLogoutV1 = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    { url: `/api/v1/auth/logout`, method: 'POST', signal },
    options
  );
};

export const getAuthControllerLogoutV1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerLogoutV1>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerLogoutV1>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['authControllerLogoutV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerLogoutV1>>,
    void
  > = () => {
    return authControllerLogoutV1(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerLogoutV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerLogoutV1>>
>;

export type AuthControllerLogoutV1MutationError = unknown;

/**
 * @summary Logout by revoking refresh token and clearing cookie
 */
export const useAuthControllerLogoutV1 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerLogoutV1>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerLogoutV1>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getAuthControllerLogoutV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary User registration
 */
export const authControllerRegisterV1 = (
  registerDto: RegisterDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/auth/register`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: registerDto,
      signal,
    },
    options
  );
};

export const getAuthControllerRegisterV1MutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerRegisterV1>>,
    TError,
    { data: RegisterDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerRegisterV1>>,
  TError,
  { data: RegisterDto },
  TContext
> => {
  const mutationKey = ['authControllerRegisterV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerRegisterV1>>,
    { data: RegisterDto }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerRegisterV1(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerRegisterV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerRegisterV1>>
>;
export type AuthControllerRegisterV1MutationBody = RegisterDto;
export type AuthControllerRegisterV1MutationError = void;

/**
 * @summary User registration
 */
export const useAuthControllerRegisterV1 = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerRegisterV1>>,
      TError,
      { data: RegisterDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerRegisterV1>>,
  TError,
  { data: RegisterDto },
  TContext
> => {
  const mutationOptions = getAuthControllerRegisterV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get current user info with effective permissions
 */
export const authControllerGetProfileV1 = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    { url: `/api/v1/auth/me`, method: 'GET', signal },
    options
  );
};

export const getAuthControllerGetProfileV1QueryKey = () => {
  return [`/api/v1/auth/me`] as const;
};

export const getAuthControllerGetProfileV1QueryOptions = <
  TData = Awaited<ReturnType<typeof authControllerGetProfileV1>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof authControllerGetProfileV1>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAuthControllerGetProfileV1QueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof authControllerGetProfileV1>>
  > = ({ signal }) => authControllerGetProfileV1(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authControllerGetProfileV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AuthControllerGetProfileV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof authControllerGetProfileV1>>
>;
export type AuthControllerGetProfileV1QueryError = void;

export function useAuthControllerGetProfileV1<
  TData = Awaited<ReturnType<typeof authControllerGetProfileV1>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authControllerGetProfileV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGetProfileV1>>,
          TError,
          Awaited<ReturnType<typeof authControllerGetProfileV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAuthControllerGetProfileV1<
  TData = Awaited<ReturnType<typeof authControllerGetProfileV1>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authControllerGetProfileV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGetProfileV1>>,
          TError,
          Awaited<ReturnType<typeof authControllerGetProfileV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAuthControllerGetProfileV1<
  TData = Awaited<ReturnType<typeof authControllerGetProfileV1>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authControllerGetProfileV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get current user info with effective permissions
 */

export function useAuthControllerGetProfileV1<
  TData = Awaited<ReturnType<typeof authControllerGetProfileV1>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authControllerGetProfileV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAuthControllerGetProfileV1QueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
