/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { CreateBankAccountDto, UpdateBankAccountDto } from '../model';

import { customInstance } from '../../lib/api-custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Create a bank account
 */
export const bankAccountsControllerCreateV1 = (
  createBankAccountDto: CreateBankAccountDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/bank-accounts`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createBankAccountDto,
      signal,
    },
    options
  );
};

export const getBankAccountsControllerCreateV1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof bankAccountsControllerCreateV1>>,
    TError,
    { data: CreateBankAccountDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof bankAccountsControllerCreateV1>>,
  TError,
  { data: CreateBankAccountDto },
  TContext
> => {
  const mutationKey = ['bankAccountsControllerCreateV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof bankAccountsControllerCreateV1>>,
    { data: CreateBankAccountDto }
  > = (props) => {
    const { data } = props ?? {};

    return bankAccountsControllerCreateV1(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type BankAccountsControllerCreateV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof bankAccountsControllerCreateV1>>
>;
export type BankAccountsControllerCreateV1MutationBody = CreateBankAccountDto;
export type BankAccountsControllerCreateV1MutationError = unknown;

/**
 * @summary Create a bank account
 */
export const useBankAccountsControllerCreateV1 = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof bankAccountsControllerCreateV1>>,
      TError,
      { data: CreateBankAccountDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof bankAccountsControllerCreateV1>>,
  TError,
  { data: CreateBankAccountDto },
  TContext
> => {
  const mutationOptions =
    getBankAccountsControllerCreateV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary List bank accounts for the organization
 */
export const bankAccountsControllerFindAllV1 = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    { url: `/api/v1/bank-accounts`, method: 'GET', signal },
    options
  );
};

export const getBankAccountsControllerFindAllV1QueryKey = () => {
  return [`/api/v1/bank-accounts`] as const;
};

export const getBankAccountsControllerFindAllV1QueryOptions = <
  TData = Awaited<ReturnType<typeof bankAccountsControllerFindAllV1>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof bankAccountsControllerFindAllV1>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getBankAccountsControllerFindAllV1QueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof bankAccountsControllerFindAllV1>>
  > = ({ signal }) => bankAccountsControllerFindAllV1(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof bankAccountsControllerFindAllV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BankAccountsControllerFindAllV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof bankAccountsControllerFindAllV1>>
>;
export type BankAccountsControllerFindAllV1QueryError = unknown;

export function useBankAccountsControllerFindAllV1<
  TData = Awaited<ReturnType<typeof bankAccountsControllerFindAllV1>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof bankAccountsControllerFindAllV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof bankAccountsControllerFindAllV1>>,
          TError,
          Awaited<ReturnType<typeof bankAccountsControllerFindAllV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBankAccountsControllerFindAllV1<
  TData = Awaited<ReturnType<typeof bankAccountsControllerFindAllV1>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof bankAccountsControllerFindAllV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof bankAccountsControllerFindAllV1>>,
          TError,
          Awaited<ReturnType<typeof bankAccountsControllerFindAllV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBankAccountsControllerFindAllV1<
  TData = Awaited<ReturnType<typeof bankAccountsControllerFindAllV1>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof bankAccountsControllerFindAllV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List bank accounts for the organization
 */

export function useBankAccountsControllerFindAllV1<
  TData = Awaited<ReturnType<typeof bankAccountsControllerFindAllV1>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof bankAccountsControllerFindAllV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getBankAccountsControllerFindAllV1QueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update a bank account
 */
export const bankAccountsControllerUpdateV1 = (
  id: string,
  updateBankAccountDto: UpdateBankAccountDto,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    {
      url: `/api/v1/bank-accounts/${id}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateBankAccountDto,
    },
    options
  );
};

export const getBankAccountsControllerUpdateV1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof bankAccountsControllerUpdateV1>>,
    TError,
    { id: string; data: UpdateBankAccountDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof bankAccountsControllerUpdateV1>>,
  TError,
  { id: string; data: UpdateBankAccountDto },
  TContext
> => {
  const mutationKey = ['bankAccountsControllerUpdateV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof bankAccountsControllerUpdateV1>>,
    { id: string; data: UpdateBankAccountDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return bankAccountsControllerUpdateV1(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type BankAccountsControllerUpdateV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof bankAccountsControllerUpdateV1>>
>;
export type BankAccountsControllerUpdateV1MutationBody = UpdateBankAccountDto;
export type BankAccountsControllerUpdateV1MutationError = unknown;

/**
 * @summary Update a bank account
 */
export const useBankAccountsControllerUpdateV1 = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof bankAccountsControllerUpdateV1>>,
      TError,
      { id: string; data: UpdateBankAccountDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof bankAccountsControllerUpdateV1>>,
  TError,
  { id: string; data: UpdateBankAccountDto },
  TContext
> => {
  const mutationOptions =
    getBankAccountsControllerUpdateV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Delete a bank account
 */
export const bankAccountsControllerRemoveV1 = (
  id: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    { url: `/api/v1/bank-accounts/${id}`, method: 'DELETE' },
    options
  );
};

export const getBankAccountsControllerRemoveV1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof bankAccountsControllerRemoveV1>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof bankAccountsControllerRemoveV1>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['bankAccountsControllerRemoveV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof bankAccountsControllerRemoveV1>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return bankAccountsControllerRemoveV1(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type BankAccountsControllerRemoveV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof bankAccountsControllerRemoveV1>>
>;

export type BankAccountsControllerRemoveV1MutationError = unknown;

/**
 * @summary Delete a bank account
 */
export const useBankAccountsControllerRemoveV1 = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof bankAccountsControllerRemoveV1>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof bankAccountsControllerRemoveV1>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions =
    getBankAccountsControllerRemoveV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
