/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ChatControllerGetConversationMessagesV1Params,
  CreateConversationDto,
  CreateGroupConversationDto,
} from '../model';

import { customInstance } from '../../lib/api-custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Get user conversations
 */
export const chatControllerGetConversationsV1 = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    { url: `/api/v1/chat/conversations`, method: 'GET', signal },
    options
  );
};

export const getChatControllerGetConversationsV1QueryKey = () => {
  return [`/api/v1/chat/conversations`] as const;
};

export const getChatControllerGetConversationsV1QueryOptions = <
  TData = Awaited<ReturnType<typeof chatControllerGetConversationsV1>>,
  TError = void | void,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof chatControllerGetConversationsV1>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getChatControllerGetConversationsV1QueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof chatControllerGetConversationsV1>>
  > = ({ signal }) => chatControllerGetConversationsV1(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof chatControllerGetConversationsV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ChatControllerGetConversationsV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof chatControllerGetConversationsV1>>
>;
export type ChatControllerGetConversationsV1QueryError = void | void;

export function useChatControllerGetConversationsV1<
  TData = Awaited<ReturnType<typeof chatControllerGetConversationsV1>>,
  TError = void | void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatControllerGetConversationsV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatControllerGetConversationsV1>>,
          TError,
          Awaited<ReturnType<typeof chatControllerGetConversationsV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useChatControllerGetConversationsV1<
  TData = Awaited<ReturnType<typeof chatControllerGetConversationsV1>>,
  TError = void | void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatControllerGetConversationsV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatControllerGetConversationsV1>>,
          TError,
          Awaited<ReturnType<typeof chatControllerGetConversationsV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useChatControllerGetConversationsV1<
  TData = Awaited<ReturnType<typeof chatControllerGetConversationsV1>>,
  TError = void | void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatControllerGetConversationsV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get user conversations
 */

export function useChatControllerGetConversationsV1<
  TData = Awaited<ReturnType<typeof chatControllerGetConversationsV1>>,
  TError = void | void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatControllerGetConversationsV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getChatControllerGetConversationsV1QueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Create a new 1-on-1 conversation
 */
export const chatControllerCreateConversationV1 = (
  createConversationDto: CreateConversationDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/chat/conversations`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createConversationDto,
      signal,
    },
    options
  );
};

export const getChatControllerCreateConversationV1MutationOptions = <
  TError = void | void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof chatControllerCreateConversationV1>>,
    TError,
    { data: CreateConversationDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof chatControllerCreateConversationV1>>,
  TError,
  { data: CreateConversationDto },
  TContext
> => {
  const mutationKey = ['chatControllerCreateConversationV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof chatControllerCreateConversationV1>>,
    { data: CreateConversationDto }
  > = (props) => {
    const { data } = props ?? {};

    return chatControllerCreateConversationV1(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ChatControllerCreateConversationV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof chatControllerCreateConversationV1>>
>;
export type ChatControllerCreateConversationV1MutationBody =
  CreateConversationDto;
export type ChatControllerCreateConversationV1MutationError =
  | void
  | void
  | void;

/**
 * @summary Create a new 1-on-1 conversation
 */
export const useChatControllerCreateConversationV1 = <
  TError = void | void | void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof chatControllerCreateConversationV1>>,
      TError,
      { data: CreateConversationDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof chatControllerCreateConversationV1>>,
  TError,
  { data: CreateConversationDto },
  TContext
> => {
  const mutationOptions =
    getChatControllerCreateConversationV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Create a new group conversation
 */
export const chatControllerCreateGroupConversationV1 = (
  createGroupConversationDto: CreateGroupConversationDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/chat/groups`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createGroupConversationDto,
      signal,
    },
    options
  );
};

export const getChatControllerCreateGroupConversationV1MutationOptions = <
  TError = void | void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof chatControllerCreateGroupConversationV1>>,
    TError,
    { data: CreateGroupConversationDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof chatControllerCreateGroupConversationV1>>,
  TError,
  { data: CreateGroupConversationDto },
  TContext
> => {
  const mutationKey = ['chatControllerCreateGroupConversationV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof chatControllerCreateGroupConversationV1>>,
    { data: CreateGroupConversationDto }
  > = (props) => {
    const { data } = props ?? {};

    return chatControllerCreateGroupConversationV1(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ChatControllerCreateGroupConversationV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof chatControllerCreateGroupConversationV1>>
>;
export type ChatControllerCreateGroupConversationV1MutationBody =
  CreateGroupConversationDto;
export type ChatControllerCreateGroupConversationV1MutationError =
  | void
  | void
  | void;

/**
 * @summary Create a new group conversation
 */
export const useChatControllerCreateGroupConversationV1 = <
  TError = void | void | void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof chatControllerCreateGroupConversationV1>>,
      TError,
      { data: CreateGroupConversationDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof chatControllerCreateGroupConversationV1>>,
  TError,
  { data: CreateGroupConversationDto },
  TContext
> => {
  const mutationOptions =
    getChatControllerCreateGroupConversationV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get conversation messages
 */
export const chatControllerGetConversationMessagesV1 = (
  conversationId: string,
  params: ChatControllerGetConversationMessagesV1Params,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/chat/conversations/${conversationId}/messages`,
      method: 'GET',
      params,
      signal,
    },
    options
  );
};

export const getChatControllerGetConversationMessagesV1QueryKey = (
  conversationId?: string,
  params?: ChatControllerGetConversationMessagesV1Params
) => {
  return [
    `/api/v1/chat/conversations/${conversationId}/messages`,
    ...(params ? [params] : []),
  ] as const;
};

export const getChatControllerGetConversationMessagesV1QueryOptions = <
  TData = Awaited<ReturnType<typeof chatControllerGetConversationMessagesV1>>,
  TError = void | void | void,
>(
  conversationId: string,
  params: ChatControllerGetConversationMessagesV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatControllerGetConversationMessagesV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getChatControllerGetConversationMessagesV1QueryKey(conversationId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof chatControllerGetConversationMessagesV1>>
  > = ({ signal }) =>
    chatControllerGetConversationMessagesV1(
      conversationId,
      params,
      requestOptions,
      signal
    );

  return {
    queryKey,
    queryFn,
    enabled: !!conversationId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof chatControllerGetConversationMessagesV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ChatControllerGetConversationMessagesV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof chatControllerGetConversationMessagesV1>>
>;
export type ChatControllerGetConversationMessagesV1QueryError =
  | void
  | void
  | void;

export function useChatControllerGetConversationMessagesV1<
  TData = Awaited<ReturnType<typeof chatControllerGetConversationMessagesV1>>,
  TError = void | void | void,
>(
  conversationId: string,
  params: ChatControllerGetConversationMessagesV1Params,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatControllerGetConversationMessagesV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatControllerGetConversationMessagesV1>>,
          TError,
          Awaited<ReturnType<typeof chatControllerGetConversationMessagesV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useChatControllerGetConversationMessagesV1<
  TData = Awaited<ReturnType<typeof chatControllerGetConversationMessagesV1>>,
  TError = void | void | void,
>(
  conversationId: string,
  params: ChatControllerGetConversationMessagesV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatControllerGetConversationMessagesV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatControllerGetConversationMessagesV1>>,
          TError,
          Awaited<ReturnType<typeof chatControllerGetConversationMessagesV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useChatControllerGetConversationMessagesV1<
  TData = Awaited<ReturnType<typeof chatControllerGetConversationMessagesV1>>,
  TError = void | void | void,
>(
  conversationId: string,
  params: ChatControllerGetConversationMessagesV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatControllerGetConversationMessagesV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get conversation messages
 */

export function useChatControllerGetConversationMessagesV1<
  TData = Awaited<ReturnType<typeof chatControllerGetConversationMessagesV1>>,
  TError = void | void | void,
>(
  conversationId: string,
  params: ChatControllerGetConversationMessagesV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatControllerGetConversationMessagesV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getChatControllerGetConversationMessagesV1QueryOptions(
    conversationId,
    params,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
