/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { CreateLeadNoteDto } from '../model';

import { customInstance } from '../../lib/api-custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary List lead notes
 */
export const leadNotesControllerFindAllV1 = (
  organizationId: string,
  leadId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/leads/${leadId}/notes`,
      method: 'GET',
      signal,
    },
    options
  );
};

export const getLeadNotesControllerFindAllV1QueryKey = (
  organizationId?: string,
  leadId?: string
) => {
  return [
    `/api/v1/organizations/${organizationId}/leads/${leadId}/notes`,
  ] as const;
};

export const getLeadNotesControllerFindAllV1QueryOptions = <
  TData = Awaited<ReturnType<typeof leadNotesControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  leadId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leadNotesControllerFindAllV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getLeadNotesControllerFindAllV1QueryKey(organizationId, leadId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof leadNotesControllerFindAllV1>>
  > = ({ signal }) =>
    leadNotesControllerFindAllV1(
      organizationId,
      leadId,
      requestOptions,
      signal
    );

  return {
    queryKey,
    queryFn,
    enabled: !!(organizationId && leadId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof leadNotesControllerFindAllV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type LeadNotesControllerFindAllV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof leadNotesControllerFindAllV1>>
>;
export type LeadNotesControllerFindAllV1QueryError = unknown;

export function useLeadNotesControllerFindAllV1<
  TData = Awaited<ReturnType<typeof leadNotesControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  leadId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leadNotesControllerFindAllV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof leadNotesControllerFindAllV1>>,
          TError,
          Awaited<ReturnType<typeof leadNotesControllerFindAllV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLeadNotesControllerFindAllV1<
  TData = Awaited<ReturnType<typeof leadNotesControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  leadId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leadNotesControllerFindAllV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof leadNotesControllerFindAllV1>>,
          TError,
          Awaited<ReturnType<typeof leadNotesControllerFindAllV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLeadNotesControllerFindAllV1<
  TData = Awaited<ReturnType<typeof leadNotesControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  leadId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leadNotesControllerFindAllV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List lead notes
 */

export function useLeadNotesControllerFindAllV1<
  TData = Awaited<ReturnType<typeof leadNotesControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  leadId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leadNotesControllerFindAllV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getLeadNotesControllerFindAllV1QueryOptions(
    organizationId,
    leadId,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Create lead note
 */
export const leadNotesControllerCreateV1 = (
  organizationId: string,
  leadId: string,
  createLeadNoteDto: CreateLeadNoteDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/leads/${leadId}/notes`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createLeadNoteDto,
      signal,
    },
    options
  );
};

export const getLeadNotesControllerCreateV1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof leadNotesControllerCreateV1>>,
    TError,
    { organizationId: string; leadId: string; data: CreateLeadNoteDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof leadNotesControllerCreateV1>>,
  TError,
  { organizationId: string; leadId: string; data: CreateLeadNoteDto },
  TContext
> => {
  const mutationKey = ['leadNotesControllerCreateV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof leadNotesControllerCreateV1>>,
    { organizationId: string; leadId: string; data: CreateLeadNoteDto }
  > = (props) => {
    const { organizationId, leadId, data } = props ?? {};

    return leadNotesControllerCreateV1(
      organizationId,
      leadId,
      data,
      requestOptions
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type LeadNotesControllerCreateV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof leadNotesControllerCreateV1>>
>;
export type LeadNotesControllerCreateV1MutationBody = CreateLeadNoteDto;
export type LeadNotesControllerCreateV1MutationError = unknown;

/**
 * @summary Create lead note
 */
export const useLeadNotesControllerCreateV1 = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof leadNotesControllerCreateV1>>,
      TError,
      { organizationId: string; leadId: string; data: CreateLeadNoteDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof leadNotesControllerCreateV1>>,
  TError,
  { organizationId: string; leadId: string; data: CreateLeadNoteDto },
  TContext
> => {
  const mutationOptions =
    getLeadNotesControllerCreateV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Delete lead note
 */
export const leadNotesControllerRemoveV1 = (
  organizationId: string,
  leadId: string,
  noteId: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/leads/${leadId}/notes/${noteId}`,
      method: 'DELETE',
    },
    options
  );
};

export const getLeadNotesControllerRemoveV1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof leadNotesControllerRemoveV1>>,
    TError,
    { organizationId: string; leadId: string; noteId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof leadNotesControllerRemoveV1>>,
  TError,
  { organizationId: string; leadId: string; noteId: string },
  TContext
> => {
  const mutationKey = ['leadNotesControllerRemoveV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof leadNotesControllerRemoveV1>>,
    { organizationId: string; leadId: string; noteId: string }
  > = (props) => {
    const { organizationId, leadId, noteId } = props ?? {};

    return leadNotesControllerRemoveV1(
      organizationId,
      leadId,
      noteId,
      requestOptions
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type LeadNotesControllerRemoveV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof leadNotesControllerRemoveV1>>
>;

export type LeadNotesControllerRemoveV1MutationError = unknown;

/**
 * @summary Delete lead note
 */
export const useLeadNotesControllerRemoveV1 = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof leadNotesControllerRemoveV1>>,
      TError,
      { organizationId: string; leadId: string; noteId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof leadNotesControllerRemoveV1>>,
  TError,
  { organizationId: string; leadId: string; noteId: string },
  TContext
> => {
  const mutationOptions =
    getLeadNotesControllerRemoveV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
