/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  BulkCreateLeadsDto,
  BulkUpdateLeadsDto,
  CreateLeadDto,
  LeadsControllerExportAllV1Params,
  LeadsControllerFindAllV1Params,
  UpdateLeadDto,
} from '../model';

import { customInstance } from '../../lib/api-custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Create a lead in an organization
 */
export const leadsControllerCreateV1 = (
  organizationId: string,
  createLeadDto: CreateLeadDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/leads`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createLeadDto,
      signal,
    },
    options
  );
};

export const getLeadsControllerCreateV1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof leadsControllerCreateV1>>,
    TError,
    { organizationId: string; data: CreateLeadDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof leadsControllerCreateV1>>,
  TError,
  { organizationId: string; data: CreateLeadDto },
  TContext
> => {
  const mutationKey = ['leadsControllerCreateV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof leadsControllerCreateV1>>,
    { organizationId: string; data: CreateLeadDto }
  > = (props) => {
    const { organizationId, data } = props ?? {};

    return leadsControllerCreateV1(organizationId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LeadsControllerCreateV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof leadsControllerCreateV1>>
>;
export type LeadsControllerCreateV1MutationBody = CreateLeadDto;
export type LeadsControllerCreateV1MutationError = unknown;

/**
 * @summary Create a lead in an organization
 */
export const useLeadsControllerCreateV1 = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof leadsControllerCreateV1>>,
      TError,
      { organizationId: string; data: CreateLeadDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof leadsControllerCreateV1>>,
  TError,
  { organizationId: string; data: CreateLeadDto },
  TContext
> => {
  const mutationOptions = getLeadsControllerCreateV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary List leads in organization with pagination
 */
export const leadsControllerFindAllV1 = (
  organizationId: string,
  params?: LeadsControllerFindAllV1Params,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/leads`,
      method: 'GET',
      params,
      signal,
    },
    options
  );
};

export const getLeadsControllerFindAllV1QueryKey = (
  organizationId?: string,
  params?: LeadsControllerFindAllV1Params
) => {
  return [
    `/api/v1/organizations/${organizationId}/leads`,
    ...(params ? [params] : []),
  ] as const;
};

export const getLeadsControllerFindAllV1QueryOptions = <
  TData = Awaited<ReturnType<typeof leadsControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  params?: LeadsControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leadsControllerFindAllV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getLeadsControllerFindAllV1QueryKey(organizationId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof leadsControllerFindAllV1>>
  > = ({ signal }) =>
    leadsControllerFindAllV1(organizationId, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!organizationId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof leadsControllerFindAllV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type LeadsControllerFindAllV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof leadsControllerFindAllV1>>
>;
export type LeadsControllerFindAllV1QueryError = unknown;

export function useLeadsControllerFindAllV1<
  TData = Awaited<ReturnType<typeof leadsControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  params: undefined | LeadsControllerFindAllV1Params,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leadsControllerFindAllV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof leadsControllerFindAllV1>>,
          TError,
          Awaited<ReturnType<typeof leadsControllerFindAllV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLeadsControllerFindAllV1<
  TData = Awaited<ReturnType<typeof leadsControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  params?: LeadsControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leadsControllerFindAllV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof leadsControllerFindAllV1>>,
          TError,
          Awaited<ReturnType<typeof leadsControllerFindAllV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLeadsControllerFindAllV1<
  TData = Awaited<ReturnType<typeof leadsControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  params?: LeadsControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leadsControllerFindAllV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List leads in organization with pagination
 */

export function useLeadsControllerFindAllV1<
  TData = Awaited<ReturnType<typeof leadsControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  params?: LeadsControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leadsControllerFindAllV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getLeadsControllerFindAllV1QueryOptions(
    organizationId,
    params,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Export all matching leads in organization
 */
export const leadsControllerExportAllV1 = (
  organizationId: string,
  params?: LeadsControllerExportAllV1Params,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/leads/export`,
      method: 'GET',
      params,
      signal,
    },
    options
  );
};

export const getLeadsControllerExportAllV1QueryKey = (
  organizationId?: string,
  params?: LeadsControllerExportAllV1Params
) => {
  return [
    `/api/v1/organizations/${organizationId}/leads/export`,
    ...(params ? [params] : []),
  ] as const;
};

export const getLeadsControllerExportAllV1QueryOptions = <
  TData = Awaited<ReturnType<typeof leadsControllerExportAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  params?: LeadsControllerExportAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leadsControllerExportAllV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getLeadsControllerExportAllV1QueryKey(organizationId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof leadsControllerExportAllV1>>
  > = ({ signal }) =>
    leadsControllerExportAllV1(organizationId, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!organizationId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof leadsControllerExportAllV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type LeadsControllerExportAllV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof leadsControllerExportAllV1>>
>;
export type LeadsControllerExportAllV1QueryError = unknown;

export function useLeadsControllerExportAllV1<
  TData = Awaited<ReturnType<typeof leadsControllerExportAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  params: undefined | LeadsControllerExportAllV1Params,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leadsControllerExportAllV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof leadsControllerExportAllV1>>,
          TError,
          Awaited<ReturnType<typeof leadsControllerExportAllV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLeadsControllerExportAllV1<
  TData = Awaited<ReturnType<typeof leadsControllerExportAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  params?: LeadsControllerExportAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leadsControllerExportAllV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof leadsControllerExportAllV1>>,
          TError,
          Awaited<ReturnType<typeof leadsControllerExportAllV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLeadsControllerExportAllV1<
  TData = Awaited<ReturnType<typeof leadsControllerExportAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  params?: LeadsControllerExportAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leadsControllerExportAllV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Export all matching leads in organization
 */

export function useLeadsControllerExportAllV1<
  TData = Awaited<ReturnType<typeof leadsControllerExportAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  params?: LeadsControllerExportAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leadsControllerExportAllV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getLeadsControllerExportAllV1QueryOptions(
    organizationId,
    params,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get a single lead from an organization
 */
export const leadsControllerFindOneV1 = (
  organizationId: string,
  leadId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/leads/${leadId}`,
      method: 'GET',
      signal,
    },
    options
  );
};

export const getLeadsControllerFindOneV1QueryKey = (
  organizationId?: string,
  leadId?: string
) => {
  return [`/api/v1/organizations/${organizationId}/leads/${leadId}`] as const;
};

export const getLeadsControllerFindOneV1QueryOptions = <
  TData = Awaited<ReturnType<typeof leadsControllerFindOneV1>>,
  TError = void,
>(
  organizationId: string,
  leadId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leadsControllerFindOneV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getLeadsControllerFindOneV1QueryKey(organizationId, leadId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof leadsControllerFindOneV1>>
  > = ({ signal }) =>
    leadsControllerFindOneV1(organizationId, leadId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(organizationId && leadId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof leadsControllerFindOneV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type LeadsControllerFindOneV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof leadsControllerFindOneV1>>
>;
export type LeadsControllerFindOneV1QueryError = void;

export function useLeadsControllerFindOneV1<
  TData = Awaited<ReturnType<typeof leadsControllerFindOneV1>>,
  TError = void,
>(
  organizationId: string,
  leadId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leadsControllerFindOneV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof leadsControllerFindOneV1>>,
          TError,
          Awaited<ReturnType<typeof leadsControllerFindOneV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLeadsControllerFindOneV1<
  TData = Awaited<ReturnType<typeof leadsControllerFindOneV1>>,
  TError = void,
>(
  organizationId: string,
  leadId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leadsControllerFindOneV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof leadsControllerFindOneV1>>,
          TError,
          Awaited<ReturnType<typeof leadsControllerFindOneV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLeadsControllerFindOneV1<
  TData = Awaited<ReturnType<typeof leadsControllerFindOneV1>>,
  TError = void,
>(
  organizationId: string,
  leadId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leadsControllerFindOneV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a single lead from an organization
 */

export function useLeadsControllerFindOneV1<
  TData = Awaited<ReturnType<typeof leadsControllerFindOneV1>>,
  TError = void,
>(
  organizationId: string,
  leadId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leadsControllerFindOneV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getLeadsControllerFindOneV1QueryOptions(
    organizationId,
    leadId,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update a lead in an organization
 */
export const leadsControllerUpdateV1 = (
  organizationId: string,
  leadId: string,
  updateLeadDto: UpdateLeadDto,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/leads/${leadId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateLeadDto,
    },
    options
  );
};

export const getLeadsControllerUpdateV1MutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof leadsControllerUpdateV1>>,
    TError,
    { organizationId: string; leadId: string; data: UpdateLeadDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof leadsControllerUpdateV1>>,
  TError,
  { organizationId: string; leadId: string; data: UpdateLeadDto },
  TContext
> => {
  const mutationKey = ['leadsControllerUpdateV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof leadsControllerUpdateV1>>,
    { organizationId: string; leadId: string; data: UpdateLeadDto }
  > = (props) => {
    const { organizationId, leadId, data } = props ?? {};

    return leadsControllerUpdateV1(
      organizationId,
      leadId,
      data,
      requestOptions
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type LeadsControllerUpdateV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof leadsControllerUpdateV1>>
>;
export type LeadsControllerUpdateV1MutationBody = UpdateLeadDto;
export type LeadsControllerUpdateV1MutationError = void;

/**
 * @summary Update a lead in an organization
 */
export const useLeadsControllerUpdateV1 = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof leadsControllerUpdateV1>>,
      TError,
      { organizationId: string; leadId: string; data: UpdateLeadDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof leadsControllerUpdateV1>>,
  TError,
  { organizationId: string; leadId: string; data: UpdateLeadDto },
  TContext
> => {
  const mutationOptions = getLeadsControllerUpdateV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Delete a lead from an organization
 */
export const leadsControllerRemoveV1 = (
  organizationId: string,
  leadId: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/leads/${leadId}`,
      method: 'DELETE',
    },
    options
  );
};

export const getLeadsControllerRemoveV1MutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof leadsControllerRemoveV1>>,
    TError,
    { organizationId: string; leadId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof leadsControllerRemoveV1>>,
  TError,
  { organizationId: string; leadId: string },
  TContext
> => {
  const mutationKey = ['leadsControllerRemoveV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof leadsControllerRemoveV1>>,
    { organizationId: string; leadId: string }
  > = (props) => {
    const { organizationId, leadId } = props ?? {};

    return leadsControllerRemoveV1(organizationId, leadId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LeadsControllerRemoveV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof leadsControllerRemoveV1>>
>;

export type LeadsControllerRemoveV1MutationError = void;

/**
 * @summary Delete a lead from an organization
 */
export const useLeadsControllerRemoveV1 = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof leadsControllerRemoveV1>>,
      TError,
      { organizationId: string; leadId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof leadsControllerRemoveV1>>,
  TError,
  { organizationId: string; leadId: string },
  TContext
> => {
  const mutationOptions = getLeadsControllerRemoveV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Bulk create leads in an organization
 */
export const leadsControllerBulkCreateV1 = (
  organizationId: string,
  bulkCreateLeadsDto: BulkCreateLeadsDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/leads/bulk-create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: bulkCreateLeadsDto,
      signal,
    },
    options
  );
};

export const getLeadsControllerBulkCreateV1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof leadsControllerBulkCreateV1>>,
    TError,
    { organizationId: string; data: BulkCreateLeadsDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof leadsControllerBulkCreateV1>>,
  TError,
  { organizationId: string; data: BulkCreateLeadsDto },
  TContext
> => {
  const mutationKey = ['leadsControllerBulkCreateV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof leadsControllerBulkCreateV1>>,
    { organizationId: string; data: BulkCreateLeadsDto }
  > = (props) => {
    const { organizationId, data } = props ?? {};

    return leadsControllerBulkCreateV1(organizationId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LeadsControllerBulkCreateV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof leadsControllerBulkCreateV1>>
>;
export type LeadsControllerBulkCreateV1MutationBody = BulkCreateLeadsDto;
export type LeadsControllerBulkCreateV1MutationError = unknown;

/**
 * @summary Bulk create leads in an organization
 */
export const useLeadsControllerBulkCreateV1 = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof leadsControllerBulkCreateV1>>,
      TError,
      { organizationId: string; data: BulkCreateLeadsDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof leadsControllerBulkCreateV1>>,
  TError,
  { organizationId: string; data: BulkCreateLeadsDto },
  TContext
> => {
  const mutationOptions =
    getLeadsControllerBulkCreateV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Bulk update leads in an organization
 */
export const leadsControllerBulkUpdateV1 = (
  organizationId: string,
  bulkUpdateLeadsDto: BulkUpdateLeadsDto,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/leads/bulk`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: bulkUpdateLeadsDto,
    },
    options
  );
};

export const getLeadsControllerBulkUpdateV1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof leadsControllerBulkUpdateV1>>,
    TError,
    { organizationId: string; data: BulkUpdateLeadsDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof leadsControllerBulkUpdateV1>>,
  TError,
  { organizationId: string; data: BulkUpdateLeadsDto },
  TContext
> => {
  const mutationKey = ['leadsControllerBulkUpdateV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof leadsControllerBulkUpdateV1>>,
    { organizationId: string; data: BulkUpdateLeadsDto }
  > = (props) => {
    const { organizationId, data } = props ?? {};

    return leadsControllerBulkUpdateV1(organizationId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LeadsControllerBulkUpdateV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof leadsControllerBulkUpdateV1>>
>;
export type LeadsControllerBulkUpdateV1MutationBody = BulkUpdateLeadsDto;
export type LeadsControllerBulkUpdateV1MutationError = unknown;

/**
 * @summary Bulk update leads in an organization
 */
export const useLeadsControllerBulkUpdateV1 = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof leadsControllerBulkUpdateV1>>,
      TError,
      { organizationId: string; data: BulkUpdateLeadsDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof leadsControllerBulkUpdateV1>>,
  TError,
  { organizationId: string; data: BulkUpdateLeadsDto },
  TContext
> => {
  const mutationOptions =
    getLeadsControllerBulkUpdateV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
