/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  CreateLeadSourceDto,
  LeadSourcesControllerFindAllV1Params,
  UpdateLeadSourceDto,
} from '../model';

import { customInstance } from '../../lib/api-custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary List organization lead sources
 */
export const leadSourcesControllerFindAllV1 = (
  organizationId: string,
  params: LeadSourcesControllerFindAllV1Params,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/lead-sources`,
      method: 'GET',
      params,
      signal,
    },
    options
  );
};

export const getLeadSourcesControllerFindAllV1QueryKey = (
  organizationId?: string,
  params?: LeadSourcesControllerFindAllV1Params
) => {
  return [
    `/api/v1/organizations/${organizationId}/lead-sources`,
    ...(params ? [params] : []),
  ] as const;
};

export const getLeadSourcesControllerFindAllV1QueryOptions = <
  TData = Awaited<ReturnType<typeof leadSourcesControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  params: LeadSourcesControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leadSourcesControllerFindAllV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getLeadSourcesControllerFindAllV1QueryKey(organizationId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof leadSourcesControllerFindAllV1>>
  > = ({ signal }) =>
    leadSourcesControllerFindAllV1(
      organizationId,
      params,
      requestOptions,
      signal
    );

  return {
    queryKey,
    queryFn,
    enabled: !!organizationId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof leadSourcesControllerFindAllV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type LeadSourcesControllerFindAllV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof leadSourcesControllerFindAllV1>>
>;
export type LeadSourcesControllerFindAllV1QueryError = unknown;

export function useLeadSourcesControllerFindAllV1<
  TData = Awaited<ReturnType<typeof leadSourcesControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  params: LeadSourcesControllerFindAllV1Params,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leadSourcesControllerFindAllV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof leadSourcesControllerFindAllV1>>,
          TError,
          Awaited<ReturnType<typeof leadSourcesControllerFindAllV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLeadSourcesControllerFindAllV1<
  TData = Awaited<ReturnType<typeof leadSourcesControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  params: LeadSourcesControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leadSourcesControllerFindAllV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof leadSourcesControllerFindAllV1>>,
          TError,
          Awaited<ReturnType<typeof leadSourcesControllerFindAllV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLeadSourcesControllerFindAllV1<
  TData = Awaited<ReturnType<typeof leadSourcesControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  params: LeadSourcesControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leadSourcesControllerFindAllV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List organization lead sources
 */

export function useLeadSourcesControllerFindAllV1<
  TData = Awaited<ReturnType<typeof leadSourcesControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  params: LeadSourcesControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leadSourcesControllerFindAllV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getLeadSourcesControllerFindAllV1QueryOptions(
    organizationId,
    params,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Create organization lead source
 */
export const leadSourcesControllerCreateV1 = (
  organizationId: string,
  createLeadSourceDto: CreateLeadSourceDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/lead-sources`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createLeadSourceDto,
      signal,
    },
    options
  );
};

export const getLeadSourcesControllerCreateV1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof leadSourcesControllerCreateV1>>,
    TError,
    { organizationId: string; data: CreateLeadSourceDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof leadSourcesControllerCreateV1>>,
  TError,
  { organizationId: string; data: CreateLeadSourceDto },
  TContext
> => {
  const mutationKey = ['leadSourcesControllerCreateV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof leadSourcesControllerCreateV1>>,
    { organizationId: string; data: CreateLeadSourceDto }
  > = (props) => {
    const { organizationId, data } = props ?? {};

    return leadSourcesControllerCreateV1(organizationId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LeadSourcesControllerCreateV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof leadSourcesControllerCreateV1>>
>;
export type LeadSourcesControllerCreateV1MutationBody = CreateLeadSourceDto;
export type LeadSourcesControllerCreateV1MutationError = unknown;

/**
 * @summary Create organization lead source
 */
export const useLeadSourcesControllerCreateV1 = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof leadSourcesControllerCreateV1>>,
      TError,
      { organizationId: string; data: CreateLeadSourceDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof leadSourcesControllerCreateV1>>,
  TError,
  { organizationId: string; data: CreateLeadSourceDto },
  TContext
> => {
  const mutationOptions =
    getLeadSourcesControllerCreateV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Update organization lead source
 */
export const leadSourcesControllerUpdateV1 = (
  organizationId: string,
  sourceId: string,
  updateLeadSourceDto: UpdateLeadSourceDto,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/lead-sources/${sourceId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateLeadSourceDto,
    },
    options
  );
};

export const getLeadSourcesControllerUpdateV1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof leadSourcesControllerUpdateV1>>,
    TError,
    { organizationId: string; sourceId: string; data: UpdateLeadSourceDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof leadSourcesControllerUpdateV1>>,
  TError,
  { organizationId: string; sourceId: string; data: UpdateLeadSourceDto },
  TContext
> => {
  const mutationKey = ['leadSourcesControllerUpdateV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof leadSourcesControllerUpdateV1>>,
    { organizationId: string; sourceId: string; data: UpdateLeadSourceDto }
  > = (props) => {
    const { organizationId, sourceId, data } = props ?? {};

    return leadSourcesControllerUpdateV1(
      organizationId,
      sourceId,
      data,
      requestOptions
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type LeadSourcesControllerUpdateV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof leadSourcesControllerUpdateV1>>
>;
export type LeadSourcesControllerUpdateV1MutationBody = UpdateLeadSourceDto;
export type LeadSourcesControllerUpdateV1MutationError = unknown;

/**
 * @summary Update organization lead source
 */
export const useLeadSourcesControllerUpdateV1 = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof leadSourcesControllerUpdateV1>>,
      TError,
      { organizationId: string; sourceId: string; data: UpdateLeadSourceDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof leadSourcesControllerUpdateV1>>,
  TError,
  { organizationId: string; sourceId: string; data: UpdateLeadSourceDto },
  TContext
> => {
  const mutationOptions =
    getLeadSourcesControllerUpdateV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Delete organization lead source
 */
export const leadSourcesControllerRemoveV1 = (
  organizationId: string,
  sourceId: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/lead-sources/${sourceId}`,
      method: 'DELETE',
    },
    options
  );
};

export const getLeadSourcesControllerRemoveV1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof leadSourcesControllerRemoveV1>>,
    TError,
    { organizationId: string; sourceId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof leadSourcesControllerRemoveV1>>,
  TError,
  { organizationId: string; sourceId: string },
  TContext
> => {
  const mutationKey = ['leadSourcesControllerRemoveV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof leadSourcesControllerRemoveV1>>,
    { organizationId: string; sourceId: string }
  > = (props) => {
    const { organizationId, sourceId } = props ?? {};

    return leadSourcesControllerRemoveV1(
      organizationId,
      sourceId,
      requestOptions
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type LeadSourcesControllerRemoveV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof leadSourcesControllerRemoveV1>>
>;

export type LeadSourcesControllerRemoveV1MutationError = unknown;

/**
 * @summary Delete organization lead source
 */
export const useLeadSourcesControllerRemoveV1 = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof leadSourcesControllerRemoveV1>>,
      TError,
      { organizationId: string; sourceId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof leadSourcesControllerRemoveV1>>,
  TError,
  { organizationId: string; sourceId: string },
  TContext
> => {
  const mutationOptions =
    getLeadSourcesControllerRemoveV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
