/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { CreateLeadAttachmentDto } from '../model';

import { customInstance } from '../../lib/api-custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary List lead attachments
 */
export const leadAttachmentsControllerFindAllV1 = (
  organizationId: string,
  leadId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/leads/${leadId}/attachments`,
      method: 'GET',
      signal,
    },
    options
  );
};

export const getLeadAttachmentsControllerFindAllV1QueryKey = (
  organizationId?: string,
  leadId?: string
) => {
  return [
    `/api/v1/organizations/${organizationId}/leads/${leadId}/attachments`,
  ] as const;
};

export const getLeadAttachmentsControllerFindAllV1QueryOptions = <
  TData = Awaited<ReturnType<typeof leadAttachmentsControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  leadId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leadAttachmentsControllerFindAllV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getLeadAttachmentsControllerFindAllV1QueryKey(organizationId, leadId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof leadAttachmentsControllerFindAllV1>>
  > = ({ signal }) =>
    leadAttachmentsControllerFindAllV1(
      organizationId,
      leadId,
      requestOptions,
      signal
    );

  return {
    queryKey,
    queryFn,
    enabled: !!(organizationId && leadId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof leadAttachmentsControllerFindAllV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type LeadAttachmentsControllerFindAllV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof leadAttachmentsControllerFindAllV1>>
>;
export type LeadAttachmentsControllerFindAllV1QueryError = unknown;

export function useLeadAttachmentsControllerFindAllV1<
  TData = Awaited<ReturnType<typeof leadAttachmentsControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  leadId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leadAttachmentsControllerFindAllV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof leadAttachmentsControllerFindAllV1>>,
          TError,
          Awaited<ReturnType<typeof leadAttachmentsControllerFindAllV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLeadAttachmentsControllerFindAllV1<
  TData = Awaited<ReturnType<typeof leadAttachmentsControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  leadId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leadAttachmentsControllerFindAllV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof leadAttachmentsControllerFindAllV1>>,
          TError,
          Awaited<ReturnType<typeof leadAttachmentsControllerFindAllV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLeadAttachmentsControllerFindAllV1<
  TData = Awaited<ReturnType<typeof leadAttachmentsControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  leadId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leadAttachmentsControllerFindAllV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List lead attachments
 */

export function useLeadAttachmentsControllerFindAllV1<
  TData = Awaited<ReturnType<typeof leadAttachmentsControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  leadId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leadAttachmentsControllerFindAllV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getLeadAttachmentsControllerFindAllV1QueryOptions(
    organizationId,
    leadId,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Create lead attachment
 */
export const leadAttachmentsControllerCreateV1 = (
  organizationId: string,
  leadId: string,
  createLeadAttachmentDto: CreateLeadAttachmentDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/leads/${leadId}/attachments`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createLeadAttachmentDto,
      signal,
    },
    options
  );
};

export const getLeadAttachmentsControllerCreateV1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof leadAttachmentsControllerCreateV1>>,
    TError,
    { organizationId: string; leadId: string; data: CreateLeadAttachmentDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof leadAttachmentsControllerCreateV1>>,
  TError,
  { organizationId: string; leadId: string; data: CreateLeadAttachmentDto },
  TContext
> => {
  const mutationKey = ['leadAttachmentsControllerCreateV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof leadAttachmentsControllerCreateV1>>,
    { organizationId: string; leadId: string; data: CreateLeadAttachmentDto }
  > = (props) => {
    const { organizationId, leadId, data } = props ?? {};

    return leadAttachmentsControllerCreateV1(
      organizationId,
      leadId,
      data,
      requestOptions
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type LeadAttachmentsControllerCreateV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof leadAttachmentsControllerCreateV1>>
>;
export type LeadAttachmentsControllerCreateV1MutationBody =
  CreateLeadAttachmentDto;
export type LeadAttachmentsControllerCreateV1MutationError = unknown;

/**
 * @summary Create lead attachment
 */
export const useLeadAttachmentsControllerCreateV1 = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof leadAttachmentsControllerCreateV1>>,
      TError,
      { organizationId: string; leadId: string; data: CreateLeadAttachmentDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof leadAttachmentsControllerCreateV1>>,
  TError,
  { organizationId: string; leadId: string; data: CreateLeadAttachmentDto },
  TContext
> => {
  const mutationOptions =
    getLeadAttachmentsControllerCreateV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Delete lead attachment
 */
export const leadAttachmentsControllerRemoveV1 = (
  organizationId: string,
  leadId: string,
  attachmentId: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/leads/${leadId}/attachments/${attachmentId}`,
      method: 'DELETE',
    },
    options
  );
};

export const getLeadAttachmentsControllerRemoveV1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof leadAttachmentsControllerRemoveV1>>,
    TError,
    { organizationId: string; leadId: string; attachmentId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof leadAttachmentsControllerRemoveV1>>,
  TError,
  { organizationId: string; leadId: string; attachmentId: string },
  TContext
> => {
  const mutationKey = ['leadAttachmentsControllerRemoveV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof leadAttachmentsControllerRemoveV1>>,
    { organizationId: string; leadId: string; attachmentId: string }
  > = (props) => {
    const { organizationId, leadId, attachmentId } = props ?? {};

    return leadAttachmentsControllerRemoveV1(
      organizationId,
      leadId,
      attachmentId,
      requestOptions
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type LeadAttachmentsControllerRemoveV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof leadAttachmentsControllerRemoveV1>>
>;

export type LeadAttachmentsControllerRemoveV1MutationError = unknown;

/**
 * @summary Delete lead attachment
 */
export const useLeadAttachmentsControllerRemoveV1 = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof leadAttachmentsControllerRemoveV1>>,
      TError,
      { organizationId: string; leadId: string; attachmentId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof leadAttachmentsControllerRemoveV1>>,
  TError,
  { organizationId: string; leadId: string; attachmentId: string },
  TContext
> => {
  const mutationOptions =
    getLeadAttachmentsControllerRemoveV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
