/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type {
  CreatePermissionOverrideDto,
  MembershipAccessControlControllerAssignRoleV1200,
  MembershipAccessControlControllerCreatePermissionOverrideV1201,
  UpdateMemberRoleDto,
} from '../model';

import { customInstance } from '../../lib/api-custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Updates the role assigned to an organization member. The new role must belong to the same organization.
 * @summary Assign a role to a member
 */
export const membershipAccessControlControllerAssignRoleV1 = (
  orgId: string,
  membershipId: string,
  updateMemberRoleDto: UpdateMemberRoleDto,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<MembershipAccessControlControllerAssignRoleV1200>(
    {
      url: `/api/v1/organizations/${orgId}/memberships/${membershipId}/role`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateMemberRoleDto,
    },
    options
  );
};

export const getMembershipAccessControlControllerAssignRoleV1MutationOptions = <
  TError = void | void | void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof membershipAccessControlControllerAssignRoleV1>>,
    TError,
    { orgId: string; membershipId: string; data: UpdateMemberRoleDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof membershipAccessControlControllerAssignRoleV1>>,
  TError,
  { orgId: string; membershipId: string; data: UpdateMemberRoleDto },
  TContext
> => {
  const mutationKey = ['membershipAccessControlControllerAssignRoleV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof membershipAccessControlControllerAssignRoleV1>>,
    { orgId: string; membershipId: string; data: UpdateMemberRoleDto }
  > = (props) => {
    const { orgId, membershipId, data } = props ?? {};

    return membershipAccessControlControllerAssignRoleV1(
      orgId,
      membershipId,
      data,
      requestOptions
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type MembershipAccessControlControllerAssignRoleV1MutationResult =
  NonNullable<
    Awaited<ReturnType<typeof membershipAccessControlControllerAssignRoleV1>>
  >;
export type MembershipAccessControlControllerAssignRoleV1MutationBody =
  UpdateMemberRoleDto;
export type MembershipAccessControlControllerAssignRoleV1MutationError =
  | void
  | void
  | void
  | void;

/**
 * @summary Assign a role to a member
 */
export const useMembershipAccessControlControllerAssignRoleV1 = <
  TError = void | void | void | void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof membershipAccessControlControllerAssignRoleV1>>,
      TError,
      { orgId: string; membershipId: string; data: UpdateMemberRoleDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof membershipAccessControlControllerAssignRoleV1>>,
  TError,
  { orgId: string; membershipId: string; data: UpdateMemberRoleDto },
  TContext
> => {
  const mutationOptions =
    getMembershipAccessControlControllerAssignRoleV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Creates or updates a permission override for a member. Overrides can grant or revoke specific permissions regardless of the member's role.
 * @summary Create or update a permission override for a member
 */
export const membershipAccessControlControllerCreatePermissionOverrideV1 = (
  orgId: string,
  membershipId: string,
  createPermissionOverrideDto: CreatePermissionOverrideDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<MembershipAccessControlControllerCreatePermissionOverrideV1201>(
    {
      url: `/api/v1/organizations/${orgId}/memberships/${membershipId}/overrides`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createPermissionOverrideDto,
      signal,
    },
    options
  );
};

export const getMembershipAccessControlControllerCreatePermissionOverrideV1MutationOptions =
  <TError = void | void | void | void, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<
          typeof membershipAccessControlControllerCreatePermissionOverrideV1
        >
      >,
      TError,
      {
        orgId: string;
        membershipId: string;
        data: CreatePermissionOverrideDto;
      },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  }): UseMutationOptions<
    Awaited<
      ReturnType<
        typeof membershipAccessControlControllerCreatePermissionOverrideV1
      >
    >,
    TError,
    { orgId: string; membershipId: string; data: CreatePermissionOverrideDto },
    TContext
  > => {
    const mutationKey = [
      'membershipAccessControlControllerCreatePermissionOverrideV1',
    ];
    const { mutation: mutationOptions, request: requestOptions } = options
      ? options.mutation &&
        'mutationKey' in options.mutation &&
        options.mutation.mutationKey
        ? options
        : { ...options, mutation: { ...options.mutation, mutationKey } }
      : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
      Awaited<
        ReturnType<
          typeof membershipAccessControlControllerCreatePermissionOverrideV1
        >
      >,
      { orgId: string; membershipId: string; data: CreatePermissionOverrideDto }
    > = (props) => {
      const { orgId, membershipId, data } = props ?? {};

      return membershipAccessControlControllerCreatePermissionOverrideV1(
        orgId,
        membershipId,
        data,
        requestOptions
      );
    };

    return { mutationFn, ...mutationOptions };
  };

export type MembershipAccessControlControllerCreatePermissionOverrideV1MutationResult =
  NonNullable<
    Awaited<
      ReturnType<
        typeof membershipAccessControlControllerCreatePermissionOverrideV1
      >
    >
  >;
export type MembershipAccessControlControllerCreatePermissionOverrideV1MutationBody =
  CreatePermissionOverrideDto;
export type MembershipAccessControlControllerCreatePermissionOverrideV1MutationError =
  void | void | void | void;

/**
 * @summary Create or update a permission override for a member
 */
export const useMembershipAccessControlControllerCreatePermissionOverrideV1 = <
  TError = void | void | void | void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<
          typeof membershipAccessControlControllerCreatePermissionOverrideV1
        >
      >,
      TError,
      {
        orgId: string;
        membershipId: string;
        data: CreatePermissionOverrideDto;
      },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<
    ReturnType<
      typeof membershipAccessControlControllerCreatePermissionOverrideV1
    >
  >,
  TError,
  { orgId: string; membershipId: string; data: CreatePermissionOverrideDto },
  TContext
> => {
  const mutationOptions =
    getMembershipAccessControlControllerCreatePermissionOverrideV1MutationOptions(
      options
    );

  return useMutation(mutationOptions, queryClient);
};
