/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ApproveMembershipRequestDto,
  CreateOrganizationDto,
  InviteToOrganizationDto,
  JoinOrganizationDto,
  OrganizationsControllerAcceptInvitationV1200,
  OrganizationsControllerCreateV1201,
  OrganizationsControllerGetInvitationByTokenV1200,
  OrganizationsControllerGetMembersV1200Item,
  OrganizationsControllerInviteV1201,
  OrganizationsControllerJoinV1201,
  OrganizationsControllerListPendingInvitationsV1200Item,
  UpdateOrganizationDto,
} from '../model';

import { customInstance } from '../../lib/api-custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Get pending join requests for an organization
 */
export const organizationsControllerGetPendingRequestsV1 = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    { url: `/api/v1/organizations/${id}/requests`, method: 'GET', signal },
    options
  );
};

export const getOrganizationsControllerGetPendingRequestsV1QueryKey = (
  id?: string
) => {
  return [`/api/v1/organizations/${id}/requests`] as const;
};

export const getOrganizationsControllerGetPendingRequestsV1QueryOptions = <
  TData = Awaited<
    ReturnType<typeof organizationsControllerGetPendingRequestsV1>
  >,
  TError = void | void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof organizationsControllerGetPendingRequestsV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getOrganizationsControllerGetPendingRequestsV1QueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof organizationsControllerGetPendingRequestsV1>>
  > = ({ signal }) =>
    organizationsControllerGetPendingRequestsV1(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof organizationsControllerGetPendingRequestsV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type OrganizationsControllerGetPendingRequestsV1QueryResult =
  NonNullable<
    Awaited<ReturnType<typeof organizationsControllerGetPendingRequestsV1>>
  >;
export type OrganizationsControllerGetPendingRequestsV1QueryError = void | void;

export function useOrganizationsControllerGetPendingRequestsV1<
  TData = Awaited<
    ReturnType<typeof organizationsControllerGetPendingRequestsV1>
  >,
  TError = void | void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof organizationsControllerGetPendingRequestsV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof organizationsControllerGetPendingRequestsV1>
          >,
          TError,
          Awaited<
            ReturnType<typeof organizationsControllerGetPendingRequestsV1>
          >
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useOrganizationsControllerGetPendingRequestsV1<
  TData = Awaited<
    ReturnType<typeof organizationsControllerGetPendingRequestsV1>
  >,
  TError = void | void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof organizationsControllerGetPendingRequestsV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof organizationsControllerGetPendingRequestsV1>
          >,
          TError,
          Awaited<
            ReturnType<typeof organizationsControllerGetPendingRequestsV1>
          >
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useOrganizationsControllerGetPendingRequestsV1<
  TData = Awaited<
    ReturnType<typeof organizationsControllerGetPendingRequestsV1>
  >,
  TError = void | void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof organizationsControllerGetPendingRequestsV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get pending join requests for an organization
 */

export function useOrganizationsControllerGetPendingRequestsV1<
  TData = Awaited<
    ReturnType<typeof organizationsControllerGetPendingRequestsV1>
  >,
  TError = void | void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof organizationsControllerGetPendingRequestsV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getOrganizationsControllerGetPendingRequestsV1QueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Create a new organization
 */
export const organizationsControllerCreateV1 = (
  createOrganizationDto: CreateOrganizationDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<OrganizationsControllerCreateV1201>(
    {
      url: `/api/v1/organizations`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createOrganizationDto,
      signal,
    },
    options
  );
};

export const getOrganizationsControllerCreateV1MutationOptions = <
  TError = void | void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizationsControllerCreateV1>>,
    TError,
    { data: CreateOrganizationDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof organizationsControllerCreateV1>>,
  TError,
  { data: CreateOrganizationDto },
  TContext
> => {
  const mutationKey = ['organizationsControllerCreateV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof organizationsControllerCreateV1>>,
    { data: CreateOrganizationDto }
  > = (props) => {
    const { data } = props ?? {};

    return organizationsControllerCreateV1(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrganizationsControllerCreateV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof organizationsControllerCreateV1>>
>;
export type OrganizationsControllerCreateV1MutationBody = CreateOrganizationDto;
export type OrganizationsControllerCreateV1MutationError = void | void | void;

/**
 * @summary Create a new organization
 */
export const useOrganizationsControllerCreateV1 = <
  TError = void | void | void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof organizationsControllerCreateV1>>,
      TError,
      { data: CreateOrganizationDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof organizationsControllerCreateV1>>,
  TError,
  { data: CreateOrganizationDto },
  TContext
> => {
  const mutationOptions =
    getOrganizationsControllerCreateV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get organization details
 */
export const organizationsControllerGetOrganizationV1 = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    { url: `/api/v1/organizations/${id}`, method: 'GET', signal },
    options
  );
};

export const getOrganizationsControllerGetOrganizationV1QueryKey = (
  id?: string
) => {
  return [`/api/v1/organizations/${id}`] as const;
};

export const getOrganizationsControllerGetOrganizationV1QueryOptions = <
  TData = Awaited<ReturnType<typeof organizationsControllerGetOrganizationV1>>,
  TError = void | void | void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof organizationsControllerGetOrganizationV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getOrganizationsControllerGetOrganizationV1QueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof organizationsControllerGetOrganizationV1>>
  > = ({ signal }) =>
    organizationsControllerGetOrganizationV1(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof organizationsControllerGetOrganizationV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type OrganizationsControllerGetOrganizationV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof organizationsControllerGetOrganizationV1>>
>;
export type OrganizationsControllerGetOrganizationV1QueryError =
  | void
  | void
  | void;

export function useOrganizationsControllerGetOrganizationV1<
  TData = Awaited<ReturnType<typeof organizationsControllerGetOrganizationV1>>,
  TError = void | void | void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof organizationsControllerGetOrganizationV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationsControllerGetOrganizationV1>>,
          TError,
          Awaited<ReturnType<typeof organizationsControllerGetOrganizationV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useOrganizationsControllerGetOrganizationV1<
  TData = Awaited<ReturnType<typeof organizationsControllerGetOrganizationV1>>,
  TError = void | void | void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof organizationsControllerGetOrganizationV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationsControllerGetOrganizationV1>>,
          TError,
          Awaited<ReturnType<typeof organizationsControllerGetOrganizationV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useOrganizationsControllerGetOrganizationV1<
  TData = Awaited<ReturnType<typeof organizationsControllerGetOrganizationV1>>,
  TError = void | void | void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof organizationsControllerGetOrganizationV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get organization details
 */

export function useOrganizationsControllerGetOrganizationV1<
  TData = Awaited<ReturnType<typeof organizationsControllerGetOrganizationV1>>,
  TError = void | void | void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof organizationsControllerGetOrganizationV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getOrganizationsControllerGetOrganizationV1QueryOptions(
    id,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update organization settings
 */
export const organizationsControllerUpdateOrganizationV1 = (
  id: string,
  updateOrganizationDto: UpdateOrganizationDto,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${id}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateOrganizationDto,
    },
    options
  );
};

export const getOrganizationsControllerUpdateOrganizationV1MutationOptions = <
  TError = void | void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizationsControllerUpdateOrganizationV1>>,
    TError,
    { id: string; data: UpdateOrganizationDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof organizationsControllerUpdateOrganizationV1>>,
  TError,
  { id: string; data: UpdateOrganizationDto },
  TContext
> => {
  const mutationKey = ['organizationsControllerUpdateOrganizationV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof organizationsControllerUpdateOrganizationV1>>,
    { id: string; data: UpdateOrganizationDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return organizationsControllerUpdateOrganizationV1(
      id,
      data,
      requestOptions
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type OrganizationsControllerUpdateOrganizationV1MutationResult =
  NonNullable<
    Awaited<ReturnType<typeof organizationsControllerUpdateOrganizationV1>>
  >;
export type OrganizationsControllerUpdateOrganizationV1MutationBody =
  UpdateOrganizationDto;
export type OrganizationsControllerUpdateOrganizationV1MutationError =
  | void
  | void
  | void;

/**
 * @summary Update organization settings
 */
export const useOrganizationsControllerUpdateOrganizationV1 = <
  TError = void | void | void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof organizationsControllerUpdateOrganizationV1>>,
      TError,
      { id: string; data: UpdateOrganizationDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof organizationsControllerUpdateOrganizationV1>>,
  TError,
  { id: string; data: UpdateOrganizationDto },
  TContext
> => {
  const mutationOptions =
    getOrganizationsControllerUpdateOrganizationV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Creates a membership request with PENDING status
 * @summary Request to join an organization
 */
export const organizationsControllerJoinV1 = (
  joinOrganizationDto: JoinOrganizationDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<OrganizationsControllerJoinV1201>(
    {
      url: `/api/v1/organizations/join`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: joinOrganizationDto,
      signal,
    },
    options
  );
};

export const getOrganizationsControllerJoinV1MutationOptions = <
  TError = void | void | void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizationsControllerJoinV1>>,
    TError,
    { data: JoinOrganizationDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof organizationsControllerJoinV1>>,
  TError,
  { data: JoinOrganizationDto },
  TContext
> => {
  const mutationKey = ['organizationsControllerJoinV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof organizationsControllerJoinV1>>,
    { data: JoinOrganizationDto }
  > = (props) => {
    const { data } = props ?? {};

    return organizationsControllerJoinV1(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrganizationsControllerJoinV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof organizationsControllerJoinV1>>
>;
export type OrganizationsControllerJoinV1MutationBody = JoinOrganizationDto;
export type OrganizationsControllerJoinV1MutationError =
  | void
  | void
  | void
  | void;

/**
 * @summary Request to join an organization
 */
export const useOrganizationsControllerJoinV1 = <
  TError = void | void | void | void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof organizationsControllerJoinV1>>,
      TError,
      { data: JoinOrganizationDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof organizationsControllerJoinV1>>,
  TError,
  { data: JoinOrganizationDto },
  TContext
> => {
  const mutationOptions =
    getOrganizationsControllerJoinV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Creates or updates an invitation record and stores the selected role for acceptance.
 * @summary Invite a user to an organization
 */
export const organizationsControllerInviteV1 = (
  organizationId: string,
  inviteToOrganizationDto: InviteToOrganizationDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<OrganizationsControllerInviteV1201>(
    {
      url: `/api/v1/organizations/${organizationId}/invite`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: inviteToOrganizationDto,
      signal,
    },
    options
  );
};

export const getOrganizationsControllerInviteV1MutationOptions = <
  TError = void | void | void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizationsControllerInviteV1>>,
    TError,
    { organizationId: string; data: InviteToOrganizationDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof organizationsControllerInviteV1>>,
  TError,
  { organizationId: string; data: InviteToOrganizationDto },
  TContext
> => {
  const mutationKey = ['organizationsControllerInviteV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof organizationsControllerInviteV1>>,
    { organizationId: string; data: InviteToOrganizationDto }
  > = (props) => {
    const { organizationId, data } = props ?? {};

    return organizationsControllerInviteV1(
      organizationId,
      data,
      requestOptions
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type OrganizationsControllerInviteV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof organizationsControllerInviteV1>>
>;
export type OrganizationsControllerInviteV1MutationBody =
  InviteToOrganizationDto;
export type OrganizationsControllerInviteV1MutationError =
  | void
  | void
  | void
  | void;

/**
 * @summary Invite a user to an organization
 */
export const useOrganizationsControllerInviteV1 = <
  TError = void | void | void | void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof organizationsControllerInviteV1>>,
      TError,
      { organizationId: string; data: InviteToOrganizationDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof organizationsControllerInviteV1>>,
  TError,
  { organizationId: string; data: InviteToOrganizationDto },
  TContext
> => {
  const mutationOptions =
    getOrganizationsControllerInviteV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Returns pending invitations for the organization. Access is restricted to owner/admin/manager users of that organization.
 * @summary List pending invitations for an organization
 */
export const organizationsControllerListPendingInvitationsV1 = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<
    OrganizationsControllerListPendingInvitationsV1200Item[]
  >(
    { url: `/api/v1/organizations/${id}/invitations`, method: 'GET', signal },
    options
  );
};

export const getOrganizationsControllerListPendingInvitationsV1QueryKey = (
  id?: string
) => {
  return [`/api/v1/organizations/${id}/invitations`] as const;
};

export const getOrganizationsControllerListPendingInvitationsV1QueryOptions = <
  TData = Awaited<
    ReturnType<typeof organizationsControllerListPendingInvitationsV1>
  >,
  TError = void | void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof organizationsControllerListPendingInvitationsV1>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getOrganizationsControllerListPendingInvitationsV1QueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof organizationsControllerListPendingInvitationsV1>>
  > = ({ signal }) =>
    organizationsControllerListPendingInvitationsV1(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof organizationsControllerListPendingInvitationsV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type OrganizationsControllerListPendingInvitationsV1QueryResult =
  NonNullable<
    Awaited<ReturnType<typeof organizationsControllerListPendingInvitationsV1>>
  >;
export type OrganizationsControllerListPendingInvitationsV1QueryError =
  | void
  | void;

export function useOrganizationsControllerListPendingInvitationsV1<
  TData = Awaited<
    ReturnType<typeof organizationsControllerListPendingInvitationsV1>
  >,
  TError = void | void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof organizationsControllerListPendingInvitationsV1>
        >,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof organizationsControllerListPendingInvitationsV1>
          >,
          TError,
          Awaited<
            ReturnType<typeof organizationsControllerListPendingInvitationsV1>
          >
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useOrganizationsControllerListPendingInvitationsV1<
  TData = Awaited<
    ReturnType<typeof organizationsControllerListPendingInvitationsV1>
  >,
  TError = void | void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof organizationsControllerListPendingInvitationsV1>
        >,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof organizationsControllerListPendingInvitationsV1>
          >,
          TError,
          Awaited<
            ReturnType<typeof organizationsControllerListPendingInvitationsV1>
          >
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useOrganizationsControllerListPendingInvitationsV1<
  TData = Awaited<
    ReturnType<typeof organizationsControllerListPendingInvitationsV1>
  >,
  TError = void | void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof organizationsControllerListPendingInvitationsV1>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List pending invitations for an organization
 */

export function useOrganizationsControllerListPendingInvitationsV1<
  TData = Awaited<
    ReturnType<typeof organizationsControllerListPendingInvitationsV1>
  >,
  TError = void | void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof organizationsControllerListPendingInvitationsV1>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getOrganizationsControllerListPendingInvitationsV1QueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Returns non-sensitive invitation details used by the invitation landing page.
 * @summary Get invitation details by token
 */
export const organizationsControllerGetInvitationByTokenV1 = (
  token: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<OrganizationsControllerGetInvitationByTokenV1200>(
    {
      url: `/api/v1/organizations/invitations/${token}`,
      method: 'GET',
      signal,
    },
    options
  );
};

export const getOrganizationsControllerGetInvitationByTokenV1QueryKey = (
  token?: string
) => {
  return [`/api/v1/organizations/invitations/${token}`] as const;
};

export const getOrganizationsControllerGetInvitationByTokenV1QueryOptions = <
  TData = Awaited<
    ReturnType<typeof organizationsControllerGetInvitationByTokenV1>
  >,
  TError = void,
>(
  token: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof organizationsControllerGetInvitationByTokenV1>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getOrganizationsControllerGetInvitationByTokenV1QueryKey(token);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof organizationsControllerGetInvitationByTokenV1>>
  > = ({ signal }) =>
    organizationsControllerGetInvitationByTokenV1(
      token,
      requestOptions,
      signal
    );

  return {
    queryKey,
    queryFn,
    enabled: !!token,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof organizationsControllerGetInvitationByTokenV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type OrganizationsControllerGetInvitationByTokenV1QueryResult =
  NonNullable<
    Awaited<ReturnType<typeof organizationsControllerGetInvitationByTokenV1>>
  >;
export type OrganizationsControllerGetInvitationByTokenV1QueryError = void;

export function useOrganizationsControllerGetInvitationByTokenV1<
  TData = Awaited<
    ReturnType<typeof organizationsControllerGetInvitationByTokenV1>
  >,
  TError = void,
>(
  token: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof organizationsControllerGetInvitationByTokenV1>
        >,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof organizationsControllerGetInvitationByTokenV1>
          >,
          TError,
          Awaited<
            ReturnType<typeof organizationsControllerGetInvitationByTokenV1>
          >
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useOrganizationsControllerGetInvitationByTokenV1<
  TData = Awaited<
    ReturnType<typeof organizationsControllerGetInvitationByTokenV1>
  >,
  TError = void,
>(
  token: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof organizationsControllerGetInvitationByTokenV1>
        >,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof organizationsControllerGetInvitationByTokenV1>
          >,
          TError,
          Awaited<
            ReturnType<typeof organizationsControllerGetInvitationByTokenV1>
          >
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useOrganizationsControllerGetInvitationByTokenV1<
  TData = Awaited<
    ReturnType<typeof organizationsControllerGetInvitationByTokenV1>
  >,
  TError = void,
>(
  token: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof organizationsControllerGetInvitationByTokenV1>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get invitation details by token
 */

export function useOrganizationsControllerGetInvitationByTokenV1<
  TData = Awaited<
    ReturnType<typeof organizationsControllerGetInvitationByTokenV1>
  >,
  TError = void,
>(
  token: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof organizationsControllerGetInvitationByTokenV1>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getOrganizationsControllerGetInvitationByTokenV1QueryOptions(
      token,
      options
    );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Accept invitation by token for authenticated users
 */
export const organizationsControllerAcceptInvitationV1 = (
  token: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<OrganizationsControllerAcceptInvitationV1200>(
    {
      url: `/api/v1/organizations/invitations/${token}/accept`,
      method: 'POST',
      signal,
    },
    options
  );
};

export const getOrganizationsControllerAcceptInvitationV1MutationOptions = <
  TError = void | void | void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizationsControllerAcceptInvitationV1>>,
    TError,
    { token: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof organizationsControllerAcceptInvitationV1>>,
  TError,
  { token: string },
  TContext
> => {
  const mutationKey = ['organizationsControllerAcceptInvitationV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof organizationsControllerAcceptInvitationV1>>,
    { token: string }
  > = (props) => {
    const { token } = props ?? {};

    return organizationsControllerAcceptInvitationV1(token, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrganizationsControllerAcceptInvitationV1MutationResult =
  NonNullable<
    Awaited<ReturnType<typeof organizationsControllerAcceptInvitationV1>>
  >;

export type OrganizationsControllerAcceptInvitationV1MutationError =
  | void
  | void
  | void
  | void;

/**
 * @summary Accept invitation by token for authenticated users
 */
export const useOrganizationsControllerAcceptInvitationV1 = <
  TError = void | void | void | void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof organizationsControllerAcceptInvitationV1>>,
      TError,
      { token: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof organizationsControllerAcceptInvitationV1>>,
  TError,
  { token: string },
  TContext
> => {
  const mutationOptions =
    getOrganizationsControllerAcceptInvitationV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Approves a pending membership request and assigns a role to the user. Requires team_members:manage permission.
 * @summary Approve a pending join request
 */
export const organizationsControllerApproveRequestV1 = (
  id: string,
  membershipId: string,
  approveMembershipRequestDto: ApproveMembershipRequestDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${id}/requests/${membershipId}/approve`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: approveMembershipRequestDto,
      signal,
    },
    options
  );
};

export const getOrganizationsControllerApproveRequestV1MutationOptions = <
  TError = void | void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizationsControllerApproveRequestV1>>,
    TError,
    { id: string; membershipId: string; data: ApproveMembershipRequestDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof organizationsControllerApproveRequestV1>>,
  TError,
  { id: string; membershipId: string; data: ApproveMembershipRequestDto },
  TContext
> => {
  const mutationKey = ['organizationsControllerApproveRequestV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof organizationsControllerApproveRequestV1>>,
    { id: string; membershipId: string; data: ApproveMembershipRequestDto }
  > = (props) => {
    const { id, membershipId, data } = props ?? {};

    return organizationsControllerApproveRequestV1(
      id,
      membershipId,
      data,
      requestOptions
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type OrganizationsControllerApproveRequestV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof organizationsControllerApproveRequestV1>>
>;
export type OrganizationsControllerApproveRequestV1MutationBody =
  ApproveMembershipRequestDto;
export type OrganizationsControllerApproveRequestV1MutationError =
  | void
  | void
  | void;

/**
 * @summary Approve a pending join request
 */
export const useOrganizationsControllerApproveRequestV1 = <
  TError = void | void | void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof organizationsControllerApproveRequestV1>>,
      TError,
      { id: string; membershipId: string; data: ApproveMembershipRequestDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof organizationsControllerApproveRequestV1>>,
  TError,
  { id: string; membershipId: string; data: ApproveMembershipRequestDto },
  TContext
> => {
  const mutationOptions =
    getOrganizationsControllerApproveRequestV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Rejects a pending membership request for an organization.
 * @summary Reject a pending join request
 */
export const organizationsControllerRejectRequestV1 = (
  id: string,
  membershipId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${id}/requests/${membershipId}/reject`,
      method: 'POST',
      signal,
    },
    options
  );
};

export const getOrganizationsControllerRejectRequestV1MutationOptions = <
  TError = void | void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizationsControllerRejectRequestV1>>,
    TError,
    { id: string; membershipId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof organizationsControllerRejectRequestV1>>,
  TError,
  { id: string; membershipId: string },
  TContext
> => {
  const mutationKey = ['organizationsControllerRejectRequestV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof organizationsControllerRejectRequestV1>>,
    { id: string; membershipId: string }
  > = (props) => {
    const { id, membershipId } = props ?? {};

    return organizationsControllerRejectRequestV1(
      id,
      membershipId,
      requestOptions
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type OrganizationsControllerRejectRequestV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof organizationsControllerRejectRequestV1>>
>;

export type OrganizationsControllerRejectRequestV1MutationError =
  | void
  | void
  | void;

/**
 * @summary Reject a pending join request
 */
export const useOrganizationsControllerRejectRequestV1 = <
  TError = void | void | void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof organizationsControllerRejectRequestV1>>,
      TError,
      { id: string; membershipId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof organizationsControllerRejectRequestV1>>,
  TError,
  { id: string; membershipId: string },
  TContext
> => {
  const mutationOptions =
    getOrganizationsControllerRejectRequestV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get all active members of an organization
 */
export const organizationsControllerGetMembersV1 = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<OrganizationsControllerGetMembersV1200Item[]>(
    { url: `/api/v1/organizations/${id}/members`, method: 'GET', signal },
    options
  );
};

export const getOrganizationsControllerGetMembersV1QueryKey = (id?: string) => {
  return [`/api/v1/organizations/${id}/members`] as const;
};

export const getOrganizationsControllerGetMembersV1QueryOptions = <
  TData = Awaited<ReturnType<typeof organizationsControllerGetMembersV1>>,
  TError = void | void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof organizationsControllerGetMembersV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getOrganizationsControllerGetMembersV1QueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof organizationsControllerGetMembersV1>>
  > = ({ signal }) =>
    organizationsControllerGetMembersV1(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof organizationsControllerGetMembersV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type OrganizationsControllerGetMembersV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof organizationsControllerGetMembersV1>>
>;
export type OrganizationsControllerGetMembersV1QueryError = void | void;

export function useOrganizationsControllerGetMembersV1<
  TData = Awaited<ReturnType<typeof organizationsControllerGetMembersV1>>,
  TError = void | void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof organizationsControllerGetMembersV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationsControllerGetMembersV1>>,
          TError,
          Awaited<ReturnType<typeof organizationsControllerGetMembersV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useOrganizationsControllerGetMembersV1<
  TData = Awaited<ReturnType<typeof organizationsControllerGetMembersV1>>,
  TError = void | void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof organizationsControllerGetMembersV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationsControllerGetMembersV1>>,
          TError,
          Awaited<ReturnType<typeof organizationsControllerGetMembersV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useOrganizationsControllerGetMembersV1<
  TData = Awaited<ReturnType<typeof organizationsControllerGetMembersV1>>,
  TError = void | void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof organizationsControllerGetMembersV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all active members of an organization
 */

export function useOrganizationsControllerGetMembersV1<
  TData = Awaited<ReturnType<typeof organizationsControllerGetMembersV1>>,
  TError = void | void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof organizationsControllerGetMembersV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getOrganizationsControllerGetMembersV1QueryOptions(
    id,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
