/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { PermissionsControllerGetAllPermissionsV1200Item } from '../model';

import { customInstance } from '../../lib/api-custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Retrieves all available system permissions sorted alphabetically by action. Used for rendering permission checklists in role creation UI.
 * @summary Get all global system permissions
 */
export const permissionsControllerGetAllPermissionsV1 = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<PermissionsControllerGetAllPermissionsV1200Item[]>(
    { url: `/api/v1/permissions`, method: 'GET', signal },
    options
  );
};

export const getPermissionsControllerGetAllPermissionsV1QueryKey = () => {
  return [`/api/v1/permissions`] as const;
};

export const getPermissionsControllerGetAllPermissionsV1QueryOptions = <
  TData = Awaited<ReturnType<typeof permissionsControllerGetAllPermissionsV1>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof permissionsControllerGetAllPermissionsV1>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPermissionsControllerGetAllPermissionsV1QueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof permissionsControllerGetAllPermissionsV1>>
  > = ({ signal }) =>
    permissionsControllerGetAllPermissionsV1(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof permissionsControllerGetAllPermissionsV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PermissionsControllerGetAllPermissionsV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof permissionsControllerGetAllPermissionsV1>>
>;
export type PermissionsControllerGetAllPermissionsV1QueryError = void;

export function usePermissionsControllerGetAllPermissionsV1<
  TData = Awaited<ReturnType<typeof permissionsControllerGetAllPermissionsV1>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof permissionsControllerGetAllPermissionsV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof permissionsControllerGetAllPermissionsV1>>,
          TError,
          Awaited<ReturnType<typeof permissionsControllerGetAllPermissionsV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePermissionsControllerGetAllPermissionsV1<
  TData = Awaited<ReturnType<typeof permissionsControllerGetAllPermissionsV1>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof permissionsControllerGetAllPermissionsV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof permissionsControllerGetAllPermissionsV1>>,
          TError,
          Awaited<ReturnType<typeof permissionsControllerGetAllPermissionsV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePermissionsControllerGetAllPermissionsV1<
  TData = Awaited<ReturnType<typeof permissionsControllerGetAllPermissionsV1>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof permissionsControllerGetAllPermissionsV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all global system permissions
 */

export function usePermissionsControllerGetAllPermissionsV1<
  TData = Awaited<ReturnType<typeof permissionsControllerGetAllPermissionsV1>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof permissionsControllerGetAllPermissionsV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getPermissionsControllerGetAllPermissionsV1QueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
