/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { CreatePipelineStageDto, UpdatePipelineStageDto } from '../model';

import { customInstance } from '../../lib/api-custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary List organization pipeline stages
 */
export const pipelineStagesControllerFindAllV1 = (
  organizationId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/pipeline-stages`,
      method: 'GET',
      signal,
    },
    options
  );
};

export const getPipelineStagesControllerFindAllV1QueryKey = (
  organizationId?: string
) => {
  return [`/api/v1/organizations/${organizationId}/pipeline-stages`] as const;
};

export const getPipelineStagesControllerFindAllV1QueryOptions = <
  TData = Awaited<ReturnType<typeof pipelineStagesControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof pipelineStagesControllerFindAllV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPipelineStagesControllerFindAllV1QueryKey(organizationId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof pipelineStagesControllerFindAllV1>>
  > = ({ signal }) =>
    pipelineStagesControllerFindAllV1(organizationId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!organizationId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof pipelineStagesControllerFindAllV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PipelineStagesControllerFindAllV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof pipelineStagesControllerFindAllV1>>
>;
export type PipelineStagesControllerFindAllV1QueryError = unknown;

export function usePipelineStagesControllerFindAllV1<
  TData = Awaited<ReturnType<typeof pipelineStagesControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof pipelineStagesControllerFindAllV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof pipelineStagesControllerFindAllV1>>,
          TError,
          Awaited<ReturnType<typeof pipelineStagesControllerFindAllV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePipelineStagesControllerFindAllV1<
  TData = Awaited<ReturnType<typeof pipelineStagesControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof pipelineStagesControllerFindAllV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof pipelineStagesControllerFindAllV1>>,
          TError,
          Awaited<ReturnType<typeof pipelineStagesControllerFindAllV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePipelineStagesControllerFindAllV1<
  TData = Awaited<ReturnType<typeof pipelineStagesControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof pipelineStagesControllerFindAllV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List organization pipeline stages
 */

export function usePipelineStagesControllerFindAllV1<
  TData = Awaited<ReturnType<typeof pipelineStagesControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof pipelineStagesControllerFindAllV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPipelineStagesControllerFindAllV1QueryOptions(
    organizationId,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Create organization pipeline stage
 */
export const pipelineStagesControllerCreateV1 = (
  organizationId: string,
  createPipelineStageDto: CreatePipelineStageDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/pipeline-stages`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createPipelineStageDto,
      signal,
    },
    options
  );
};

export const getPipelineStagesControllerCreateV1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof pipelineStagesControllerCreateV1>>,
    TError,
    { organizationId: string; data: CreatePipelineStageDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof pipelineStagesControllerCreateV1>>,
  TError,
  { organizationId: string; data: CreatePipelineStageDto },
  TContext
> => {
  const mutationKey = ['pipelineStagesControllerCreateV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof pipelineStagesControllerCreateV1>>,
    { organizationId: string; data: CreatePipelineStageDto }
  > = (props) => {
    const { organizationId, data } = props ?? {};

    return pipelineStagesControllerCreateV1(
      organizationId,
      data,
      requestOptions
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type PipelineStagesControllerCreateV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof pipelineStagesControllerCreateV1>>
>;
export type PipelineStagesControllerCreateV1MutationBody =
  CreatePipelineStageDto;
export type PipelineStagesControllerCreateV1MutationError = unknown;

/**
 * @summary Create organization pipeline stage
 */
export const usePipelineStagesControllerCreateV1 = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof pipelineStagesControllerCreateV1>>,
      TError,
      { organizationId: string; data: CreatePipelineStageDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof pipelineStagesControllerCreateV1>>,
  TError,
  { organizationId: string; data: CreatePipelineStageDto },
  TContext
> => {
  const mutationOptions =
    getPipelineStagesControllerCreateV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Update organization pipeline stage
 */
export const pipelineStagesControllerUpdateV1 = (
  organizationId: string,
  stageId: string,
  updatePipelineStageDto: UpdatePipelineStageDto,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/pipeline-stages/${stageId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updatePipelineStageDto,
    },
    options
  );
};

export const getPipelineStagesControllerUpdateV1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof pipelineStagesControllerUpdateV1>>,
    TError,
    { organizationId: string; stageId: string; data: UpdatePipelineStageDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof pipelineStagesControllerUpdateV1>>,
  TError,
  { organizationId: string; stageId: string; data: UpdatePipelineStageDto },
  TContext
> => {
  const mutationKey = ['pipelineStagesControllerUpdateV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof pipelineStagesControllerUpdateV1>>,
    { organizationId: string; stageId: string; data: UpdatePipelineStageDto }
  > = (props) => {
    const { organizationId, stageId, data } = props ?? {};

    return pipelineStagesControllerUpdateV1(
      organizationId,
      stageId,
      data,
      requestOptions
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type PipelineStagesControllerUpdateV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof pipelineStagesControllerUpdateV1>>
>;
export type PipelineStagesControllerUpdateV1MutationBody =
  UpdatePipelineStageDto;
export type PipelineStagesControllerUpdateV1MutationError = unknown;

/**
 * @summary Update organization pipeline stage
 */
export const usePipelineStagesControllerUpdateV1 = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof pipelineStagesControllerUpdateV1>>,
      TError,
      { organizationId: string; stageId: string; data: UpdatePipelineStageDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof pipelineStagesControllerUpdateV1>>,
  TError,
  { organizationId: string; stageId: string; data: UpdatePipelineStageDto },
  TContext
> => {
  const mutationOptions =
    getPipelineStagesControllerUpdateV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Delete organization pipeline stage
 */
export const pipelineStagesControllerRemoveV1 = (
  organizationId: string,
  stageId: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/pipeline-stages/${stageId}`,
      method: 'DELETE',
    },
    options
  );
};

export const getPipelineStagesControllerRemoveV1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof pipelineStagesControllerRemoveV1>>,
    TError,
    { organizationId: string; stageId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof pipelineStagesControllerRemoveV1>>,
  TError,
  { organizationId: string; stageId: string },
  TContext
> => {
  const mutationKey = ['pipelineStagesControllerRemoveV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof pipelineStagesControllerRemoveV1>>,
    { organizationId: string; stageId: string }
  > = (props) => {
    const { organizationId, stageId } = props ?? {};

    return pipelineStagesControllerRemoveV1(
      organizationId,
      stageId,
      requestOptions
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type PipelineStagesControllerRemoveV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof pipelineStagesControllerRemoveV1>>
>;

export type PipelineStagesControllerRemoveV1MutationError = unknown;

/**
 * @summary Delete organization pipeline stage
 */
export const usePipelineStagesControllerRemoveV1 = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof pipelineStagesControllerRemoveV1>>,
      TError,
      { organizationId: string; stageId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof pipelineStagesControllerRemoveV1>>,
  TError,
  { organizationId: string; stageId: string },
  TContext
> => {
  const mutationOptions =
    getPipelineStagesControllerRemoveV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
