/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  CreateProductDto,
  ProductsControllerFindAllV1Params,
  UpdateProductDto,
} from '../model';

import { customInstance } from '../../lib/api-custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Create a product in an organization
 */
export const productsControllerCreateV1 = (
  organizationId: string,
  createProductDto: CreateProductDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/products`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createProductDto,
      signal,
    },
    options
  );
};

export const getProductsControllerCreateV1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof productsControllerCreateV1>>,
    TError,
    { organizationId: string; data: CreateProductDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof productsControllerCreateV1>>,
  TError,
  { organizationId: string; data: CreateProductDto },
  TContext
> => {
  const mutationKey = ['productsControllerCreateV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof productsControllerCreateV1>>,
    { organizationId: string; data: CreateProductDto }
  > = (props) => {
    const { organizationId, data } = props ?? {};

    return productsControllerCreateV1(organizationId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ProductsControllerCreateV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof productsControllerCreateV1>>
>;
export type ProductsControllerCreateV1MutationBody = CreateProductDto;
export type ProductsControllerCreateV1MutationError = unknown;

/**
 * @summary Create a product in an organization
 */
export const useProductsControllerCreateV1 = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof productsControllerCreateV1>>,
      TError,
      { organizationId: string; data: CreateProductDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof productsControllerCreateV1>>,
  TError,
  { organizationId: string; data: CreateProductDto },
  TContext
> => {
  const mutationOptions = getProductsControllerCreateV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary List products in organization with pagination
 */
export const productsControllerFindAllV1 = (
  organizationId: string,
  params?: ProductsControllerFindAllV1Params,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/products`,
      method: 'GET',
      params,
      signal,
    },
    options
  );
};

export const getProductsControllerFindAllV1QueryKey = (
  organizationId?: string,
  params?: ProductsControllerFindAllV1Params
) => {
  return [
    `/api/v1/organizations/${organizationId}/products`,
    ...(params ? [params] : []),
  ] as const;
};

export const getProductsControllerFindAllV1QueryOptions = <
  TData = Awaited<ReturnType<typeof productsControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  params?: ProductsControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof productsControllerFindAllV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getProductsControllerFindAllV1QueryKey(organizationId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof productsControllerFindAllV1>>
  > = ({ signal }) =>
    productsControllerFindAllV1(organizationId, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!organizationId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof productsControllerFindAllV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProductsControllerFindAllV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof productsControllerFindAllV1>>
>;
export type ProductsControllerFindAllV1QueryError = unknown;

export function useProductsControllerFindAllV1<
  TData = Awaited<ReturnType<typeof productsControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  params: undefined | ProductsControllerFindAllV1Params,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof productsControllerFindAllV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof productsControllerFindAllV1>>,
          TError,
          Awaited<ReturnType<typeof productsControllerFindAllV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProductsControllerFindAllV1<
  TData = Awaited<ReturnType<typeof productsControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  params?: ProductsControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof productsControllerFindAllV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof productsControllerFindAllV1>>,
          TError,
          Awaited<ReturnType<typeof productsControllerFindAllV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProductsControllerFindAllV1<
  TData = Awaited<ReturnType<typeof productsControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  params?: ProductsControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof productsControllerFindAllV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List products in organization with pagination
 */

export function useProductsControllerFindAllV1<
  TData = Awaited<ReturnType<typeof productsControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  params?: ProductsControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof productsControllerFindAllV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getProductsControllerFindAllV1QueryOptions(
    organizationId,
    params,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get a single product from an organization
 */
export const productsControllerFindOneV1 = (
  organizationId: string,
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/products/${id}`,
      method: 'GET',
      signal,
    },
    options
  );
};

export const getProductsControllerFindOneV1QueryKey = (
  organizationId?: string,
  id?: string
) => {
  return [`/api/v1/organizations/${organizationId}/products/${id}`] as const;
};

export const getProductsControllerFindOneV1QueryOptions = <
  TData = Awaited<ReturnType<typeof productsControllerFindOneV1>>,
  TError = void,
>(
  organizationId: string,
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof productsControllerFindOneV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getProductsControllerFindOneV1QueryKey(organizationId, id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof productsControllerFindOneV1>>
  > = ({ signal }) =>
    productsControllerFindOneV1(organizationId, id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(organizationId && id),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof productsControllerFindOneV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProductsControllerFindOneV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof productsControllerFindOneV1>>
>;
export type ProductsControllerFindOneV1QueryError = void;

export function useProductsControllerFindOneV1<
  TData = Awaited<ReturnType<typeof productsControllerFindOneV1>>,
  TError = void,
>(
  organizationId: string,
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof productsControllerFindOneV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof productsControllerFindOneV1>>,
          TError,
          Awaited<ReturnType<typeof productsControllerFindOneV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProductsControllerFindOneV1<
  TData = Awaited<ReturnType<typeof productsControllerFindOneV1>>,
  TError = void,
>(
  organizationId: string,
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof productsControllerFindOneV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof productsControllerFindOneV1>>,
          TError,
          Awaited<ReturnType<typeof productsControllerFindOneV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProductsControllerFindOneV1<
  TData = Awaited<ReturnType<typeof productsControllerFindOneV1>>,
  TError = void,
>(
  organizationId: string,
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof productsControllerFindOneV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a single product from an organization
 */

export function useProductsControllerFindOneV1<
  TData = Awaited<ReturnType<typeof productsControllerFindOneV1>>,
  TError = void,
>(
  organizationId: string,
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof productsControllerFindOneV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getProductsControllerFindOneV1QueryOptions(
    organizationId,
    id,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update a product in an organization
 */
export const productsControllerUpdateV1 = (
  organizationId: string,
  id: string,
  updateProductDto: UpdateProductDto,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/products/${id}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateProductDto,
    },
    options
  );
};

export const getProductsControllerUpdateV1MutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof productsControllerUpdateV1>>,
    TError,
    { organizationId: string; id: string; data: UpdateProductDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof productsControllerUpdateV1>>,
  TError,
  { organizationId: string; id: string; data: UpdateProductDto },
  TContext
> => {
  const mutationKey = ['productsControllerUpdateV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof productsControllerUpdateV1>>,
    { organizationId: string; id: string; data: UpdateProductDto }
  > = (props) => {
    const { organizationId, id, data } = props ?? {};

    return productsControllerUpdateV1(organizationId, id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ProductsControllerUpdateV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof productsControllerUpdateV1>>
>;
export type ProductsControllerUpdateV1MutationBody = UpdateProductDto;
export type ProductsControllerUpdateV1MutationError = void;

/**
 * @summary Update a product in an organization
 */
export const useProductsControllerUpdateV1 = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof productsControllerUpdateV1>>,
      TError,
      { organizationId: string; id: string; data: UpdateProductDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof productsControllerUpdateV1>>,
  TError,
  { organizationId: string; id: string; data: UpdateProductDto },
  TContext
> => {
  const mutationOptions = getProductsControllerUpdateV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Delete a product from an organization
 */
export const productsControllerRemoveV1 = (
  organizationId: string,
  id: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/products/${id}`,
      method: 'DELETE',
    },
    options
  );
};

export const getProductsControllerRemoveV1MutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof productsControllerRemoveV1>>,
    TError,
    { organizationId: string; id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof productsControllerRemoveV1>>,
  TError,
  { organizationId: string; id: string },
  TContext
> => {
  const mutationKey = ['productsControllerRemoveV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof productsControllerRemoveV1>>,
    { organizationId: string; id: string }
  > = (props) => {
    const { organizationId, id } = props ?? {};

    return productsControllerRemoveV1(organizationId, id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ProductsControllerRemoveV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof productsControllerRemoveV1>>
>;

export type ProductsControllerRemoveV1MutationError = void;

/**
 * @summary Delete a product from an organization
 */
export const useProductsControllerRemoveV1 = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof productsControllerRemoveV1>>,
      TError,
      { organizationId: string; id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof productsControllerRemoveV1>>,
  TError,
  { organizationId: string; id: string },
  TContext
> => {
  const mutationOptions = getProductsControllerRemoveV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Add media to a product
 */
export const productsControllerAddMediaV1 = (
  organizationId: string,
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/products/${id}/media`,
      method: 'POST',
      signal,
    },
    options
  );
};

export const getProductsControllerAddMediaV1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof productsControllerAddMediaV1>>,
    TError,
    { organizationId: string; id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof productsControllerAddMediaV1>>,
  TError,
  { organizationId: string; id: string },
  TContext
> => {
  const mutationKey = ['productsControllerAddMediaV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof productsControllerAddMediaV1>>,
    { organizationId: string; id: string }
  > = (props) => {
    const { organizationId, id } = props ?? {};

    return productsControllerAddMediaV1(organizationId, id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ProductsControllerAddMediaV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof productsControllerAddMediaV1>>
>;

export type ProductsControllerAddMediaV1MutationError = unknown;

/**
 * @summary Add media to a product
 */
export const useProductsControllerAddMediaV1 = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof productsControllerAddMediaV1>>,
      TError,
      { organizationId: string; id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof productsControllerAddMediaV1>>,
  TError,
  { organizationId: string; id: string },
  TContext
> => {
  const mutationOptions =
    getProductsControllerAddMediaV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Set primary media for a product
 */
export const productsControllerSetPrimaryMediaV1 = (
  organizationId: string,
  id: string,
  mediaId: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/products/${id}/media/${mediaId}/primary`,
      method: 'PATCH',
    },
    options
  );
};

export const getProductsControllerSetPrimaryMediaV1MutationOptions = <
  TError = void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof productsControllerSetPrimaryMediaV1>>,
    TError,
    { organizationId: string; id: string; mediaId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof productsControllerSetPrimaryMediaV1>>,
  TError,
  { organizationId: string; id: string; mediaId: string },
  TContext
> => {
  const mutationKey = ['productsControllerSetPrimaryMediaV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof productsControllerSetPrimaryMediaV1>>,
    { organizationId: string; id: string; mediaId: string }
  > = (props) => {
    const { organizationId, id, mediaId } = props ?? {};

    return productsControllerSetPrimaryMediaV1(
      organizationId,
      id,
      mediaId,
      requestOptions
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type ProductsControllerSetPrimaryMediaV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof productsControllerSetPrimaryMediaV1>>
>;

export type ProductsControllerSetPrimaryMediaV1MutationError = void | void;

/**
 * @summary Set primary media for a product
 */
export const useProductsControllerSetPrimaryMediaV1 = <
  TError = void | void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof productsControllerSetPrimaryMediaV1>>,
      TError,
      { organizationId: string; id: string; mediaId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof productsControllerSetPrimaryMediaV1>>,
  TError,
  { organizationId: string; id: string; mediaId: string },
  TContext
> => {
  const mutationOptions =
    getProductsControllerSetPrimaryMediaV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Upload media files for a product
 */
export const productsControllerUploadMediaV1 = (
  organizationId: string,
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/products/${id}/media/upload`,
      method: 'POST',
      signal,
    },
    options
  );
};

export const getProductsControllerUploadMediaV1MutationOptions = <
  TError = void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof productsControllerUploadMediaV1>>,
    TError,
    { organizationId: string; id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof productsControllerUploadMediaV1>>,
  TError,
  { organizationId: string; id: string },
  TContext
> => {
  const mutationKey = ['productsControllerUploadMediaV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof productsControllerUploadMediaV1>>,
    { organizationId: string; id: string }
  > = (props) => {
    const { organizationId, id } = props ?? {};

    return productsControllerUploadMediaV1(organizationId, id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ProductsControllerUploadMediaV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof productsControllerUploadMediaV1>>
>;

export type ProductsControllerUploadMediaV1MutationError = void | void;

/**
 * @summary Upload media files for a product
 */
export const useProductsControllerUploadMediaV1 = <
  TError = void | void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof productsControllerUploadMediaV1>>,
      TError,
      { organizationId: string; id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof productsControllerUploadMediaV1>>,
  TError,
  { organizationId: string; id: string },
  TContext
> => {
  const mutationOptions =
    getProductsControllerUploadMediaV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
