/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  CreateProposalDto,
  ProposalsControllerFindAllV1Params,
  UpdateProposalDto,
} from '../model';

import { customInstance } from '../../lib/api-custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Create a proposal in an organization
 */
export const proposalsControllerCreateV1 = (
  organizationId: string,
  createProposalDto: CreateProposalDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/proposals`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createProposalDto,
      signal,
    },
    options
  );
};

export const getProposalsControllerCreateV1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof proposalsControllerCreateV1>>,
    TError,
    { organizationId: string; data: CreateProposalDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof proposalsControllerCreateV1>>,
  TError,
  { organizationId: string; data: CreateProposalDto },
  TContext
> => {
  const mutationKey = ['proposalsControllerCreateV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof proposalsControllerCreateV1>>,
    { organizationId: string; data: CreateProposalDto }
  > = (props) => {
    const { organizationId, data } = props ?? {};

    return proposalsControllerCreateV1(organizationId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ProposalsControllerCreateV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof proposalsControllerCreateV1>>
>;
export type ProposalsControllerCreateV1MutationBody = CreateProposalDto;
export type ProposalsControllerCreateV1MutationError = unknown;

/**
 * @summary Create a proposal in an organization
 */
export const useProposalsControllerCreateV1 = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof proposalsControllerCreateV1>>,
      TError,
      { organizationId: string; data: CreateProposalDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof proposalsControllerCreateV1>>,
  TError,
  { organizationId: string; data: CreateProposalDto },
  TContext
> => {
  const mutationOptions =
    getProposalsControllerCreateV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary List proposals in organization
 */
export const proposalsControllerFindAllV1 = (
  organizationId: string,
  params?: ProposalsControllerFindAllV1Params,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/proposals`,
      method: 'GET',
      params,
      signal,
    },
    options
  );
};

export const getProposalsControllerFindAllV1QueryKey = (
  organizationId?: string,
  params?: ProposalsControllerFindAllV1Params
) => {
  return [
    `/api/v1/organizations/${organizationId}/proposals`,
    ...(params ? [params] : []),
  ] as const;
};

export const getProposalsControllerFindAllV1QueryOptions = <
  TData = Awaited<ReturnType<typeof proposalsControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  params?: ProposalsControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof proposalsControllerFindAllV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getProposalsControllerFindAllV1QueryKey(organizationId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof proposalsControllerFindAllV1>>
  > = ({ signal }) =>
    proposalsControllerFindAllV1(
      organizationId,
      params,
      requestOptions,
      signal
    );

  return {
    queryKey,
    queryFn,
    enabled: !!organizationId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof proposalsControllerFindAllV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProposalsControllerFindAllV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof proposalsControllerFindAllV1>>
>;
export type ProposalsControllerFindAllV1QueryError = unknown;

export function useProposalsControllerFindAllV1<
  TData = Awaited<ReturnType<typeof proposalsControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  params: undefined | ProposalsControllerFindAllV1Params,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof proposalsControllerFindAllV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof proposalsControllerFindAllV1>>,
          TError,
          Awaited<ReturnType<typeof proposalsControllerFindAllV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProposalsControllerFindAllV1<
  TData = Awaited<ReturnType<typeof proposalsControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  params?: ProposalsControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof proposalsControllerFindAllV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof proposalsControllerFindAllV1>>,
          TError,
          Awaited<ReturnType<typeof proposalsControllerFindAllV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProposalsControllerFindAllV1<
  TData = Awaited<ReturnType<typeof proposalsControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  params?: ProposalsControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof proposalsControllerFindAllV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List proposals in organization
 */

export function useProposalsControllerFindAllV1<
  TData = Awaited<ReturnType<typeof proposalsControllerFindAllV1>>,
  TError = unknown,
>(
  organizationId: string,
  params?: ProposalsControllerFindAllV1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof proposalsControllerFindAllV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getProposalsControllerFindAllV1QueryOptions(
    organizationId,
    params,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get a single proposal from an organization
 */
export const proposalsControllerFindOneV1 = (
  organizationId: string,
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/proposals/${id}`,
      method: 'GET',
      signal,
    },
    options
  );
};

export const getProposalsControllerFindOneV1QueryKey = (
  organizationId?: string,
  id?: string
) => {
  return [`/api/v1/organizations/${organizationId}/proposals/${id}`] as const;
};

export const getProposalsControllerFindOneV1QueryOptions = <
  TData = Awaited<ReturnType<typeof proposalsControllerFindOneV1>>,
  TError = void,
>(
  organizationId: string,
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof proposalsControllerFindOneV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getProposalsControllerFindOneV1QueryKey(organizationId, id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof proposalsControllerFindOneV1>>
  > = ({ signal }) =>
    proposalsControllerFindOneV1(organizationId, id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(organizationId && id),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof proposalsControllerFindOneV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProposalsControllerFindOneV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof proposalsControllerFindOneV1>>
>;
export type ProposalsControllerFindOneV1QueryError = void;

export function useProposalsControllerFindOneV1<
  TData = Awaited<ReturnType<typeof proposalsControllerFindOneV1>>,
  TError = void,
>(
  organizationId: string,
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof proposalsControllerFindOneV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof proposalsControllerFindOneV1>>,
          TError,
          Awaited<ReturnType<typeof proposalsControllerFindOneV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProposalsControllerFindOneV1<
  TData = Awaited<ReturnType<typeof proposalsControllerFindOneV1>>,
  TError = void,
>(
  organizationId: string,
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof proposalsControllerFindOneV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof proposalsControllerFindOneV1>>,
          TError,
          Awaited<ReturnType<typeof proposalsControllerFindOneV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProposalsControllerFindOneV1<
  TData = Awaited<ReturnType<typeof proposalsControllerFindOneV1>>,
  TError = void,
>(
  organizationId: string,
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof proposalsControllerFindOneV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a single proposal from an organization
 */

export function useProposalsControllerFindOneV1<
  TData = Awaited<ReturnType<typeof proposalsControllerFindOneV1>>,
  TError = void,
>(
  organizationId: string,
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof proposalsControllerFindOneV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getProposalsControllerFindOneV1QueryOptions(
    organizationId,
    id,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update a proposal in an organization
 */
export const proposalsControllerUpdateV1 = (
  organizationId: string,
  id: string,
  updateProposalDto: UpdateProposalDto,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/proposals/${id}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateProposalDto,
    },
    options
  );
};

export const getProposalsControllerUpdateV1MutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof proposalsControllerUpdateV1>>,
    TError,
    { organizationId: string; id: string; data: UpdateProposalDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof proposalsControllerUpdateV1>>,
  TError,
  { organizationId: string; id: string; data: UpdateProposalDto },
  TContext
> => {
  const mutationKey = ['proposalsControllerUpdateV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof proposalsControllerUpdateV1>>,
    { organizationId: string; id: string; data: UpdateProposalDto }
  > = (props) => {
    const { organizationId, id, data } = props ?? {};

    return proposalsControllerUpdateV1(
      organizationId,
      id,
      data,
      requestOptions
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type ProposalsControllerUpdateV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof proposalsControllerUpdateV1>>
>;
export type ProposalsControllerUpdateV1MutationBody = UpdateProposalDto;
export type ProposalsControllerUpdateV1MutationError = void;

/**
 * @summary Update a proposal in an organization
 */
export const useProposalsControllerUpdateV1 = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof proposalsControllerUpdateV1>>,
      TError,
      { organizationId: string; id: string; data: UpdateProposalDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof proposalsControllerUpdateV1>>,
  TError,
  { organizationId: string; id: string; data: UpdateProposalDto },
  TContext
> => {
  const mutationOptions =
    getProposalsControllerUpdateV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Delete a proposal from an organization
 */
export const proposalsControllerRemoveV1 = (
  organizationId: string,
  id: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/proposals/${id}`,
      method: 'DELETE',
    },
    options
  );
};

export const getProposalsControllerRemoveV1MutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof proposalsControllerRemoveV1>>,
    TError,
    { organizationId: string; id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof proposalsControllerRemoveV1>>,
  TError,
  { organizationId: string; id: string },
  TContext
> => {
  const mutationKey = ['proposalsControllerRemoveV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof proposalsControllerRemoveV1>>,
    { organizationId: string; id: string }
  > = (props) => {
    const { organizationId, id } = props ?? {};

    return proposalsControllerRemoveV1(organizationId, id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ProposalsControllerRemoveV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof proposalsControllerRemoveV1>>
>;

export type ProposalsControllerRemoveV1MutationError = void;

/**
 * @summary Delete a proposal from an organization
 */
export const useProposalsControllerRemoveV1 = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof proposalsControllerRemoveV1>>,
      TError,
      { organizationId: string; id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof proposalsControllerRemoveV1>>,
  TError,
  { organizationId: string; id: string },
  TContext
> => {
  const mutationOptions =
    getProposalsControllerRemoveV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Verify a proposal in an organization
 */
export const proposalsControllerVerifyV1 = (
  organizationId: string,
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/organizations/${organizationId}/proposals/${id}/verify`,
      method: 'POST',
      signal,
    },
    options
  );
};

export const getProposalsControllerVerifyV1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof proposalsControllerVerifyV1>>,
    TError,
    { organizationId: string; id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof proposalsControllerVerifyV1>>,
  TError,
  { organizationId: string; id: string },
  TContext
> => {
  const mutationKey = ['proposalsControllerVerifyV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof proposalsControllerVerifyV1>>,
    { organizationId: string; id: string }
  > = (props) => {
    const { organizationId, id } = props ?? {};

    return proposalsControllerVerifyV1(organizationId, id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ProposalsControllerVerifyV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof proposalsControllerVerifyV1>>
>;

export type ProposalsControllerVerifyV1MutationError = unknown;

/**
 * @summary Verify a proposal in an organization
 */
export const useProposalsControllerVerifyV1 = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof proposalsControllerVerifyV1>>,
      TError,
      { organizationId: string; id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof proposalsControllerVerifyV1>>,
  TError,
  { organizationId: string; id: string },
  TContext
> => {
  const mutationOptions =
    getProposalsControllerVerifyV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
