/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AccessControlControllerAssignPermissionOverrideV1201,
  AccessControlControllerChangeMemberRoleV1200,
  AccessControlControllerCreateRoleV1201,
  AccessControlControllerDeleteRoleV1200,
  AccessControlControllerGetMemberPermissionBreakdownV1200,
  AccessControlControllerGetRolesV1200Item,
  AccessControlControllerUpdateRoleV1200,
  CreatePermissionOverrideDto,
  CreateRoleDto,
  UpdateMemberRoleDto,
  UpdateRoleDto,
} from '../model';

import { customInstance } from '../../lib/api-custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Retrieves all roles with their associated permissions for the specified organization
 * @summary Get all roles for an organization
 */
export const accessControlControllerGetRolesV1 = (
  orgId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<AccessControlControllerGetRolesV1200Item[]>(
    { url: `/api/v1/organizations/${orgId}/roles`, method: 'GET', signal },
    options
  );
};

export const getAccessControlControllerGetRolesV1QueryKey = (
  orgId?: string
) => {
  return [`/api/v1/organizations/${orgId}/roles`] as const;
};

export const getAccessControlControllerGetRolesV1QueryOptions = <
  TData = Awaited<ReturnType<typeof accessControlControllerGetRolesV1>>,
  TError = void | void,
>(
  orgId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof accessControlControllerGetRolesV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getAccessControlControllerGetRolesV1QueryKey(orgId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof accessControlControllerGetRolesV1>>
  > = ({ signal }) =>
    accessControlControllerGetRolesV1(orgId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!orgId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof accessControlControllerGetRolesV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AccessControlControllerGetRolesV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof accessControlControllerGetRolesV1>>
>;
export type AccessControlControllerGetRolesV1QueryError = void | void;

export function useAccessControlControllerGetRolesV1<
  TData = Awaited<ReturnType<typeof accessControlControllerGetRolesV1>>,
  TError = void | void,
>(
  orgId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof accessControlControllerGetRolesV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof accessControlControllerGetRolesV1>>,
          TError,
          Awaited<ReturnType<typeof accessControlControllerGetRolesV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAccessControlControllerGetRolesV1<
  TData = Awaited<ReturnType<typeof accessControlControllerGetRolesV1>>,
  TError = void | void,
>(
  orgId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof accessControlControllerGetRolesV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof accessControlControllerGetRolesV1>>,
          TError,
          Awaited<ReturnType<typeof accessControlControllerGetRolesV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAccessControlControllerGetRolesV1<
  TData = Awaited<ReturnType<typeof accessControlControllerGetRolesV1>>,
  TError = void | void,
>(
  orgId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof accessControlControllerGetRolesV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all roles for an organization
 */

export function useAccessControlControllerGetRolesV1<
  TData = Awaited<ReturnType<typeof accessControlControllerGetRolesV1>>,
  TError = void | void,
>(
  orgId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof accessControlControllerGetRolesV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAccessControlControllerGetRolesV1QueryOptions(
    orgId,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Creates a new role and associates it with the provided permissions. Operation is transactional.
 * @summary Create a new role for an organization
 */
export const accessControlControllerCreateRoleV1 = (
  orgId: string,
  createRoleDto: CreateRoleDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<AccessControlControllerCreateRoleV1201>(
    {
      url: `/api/v1/organizations/${orgId}/roles`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createRoleDto,
      signal,
    },
    options
  );
};

export const getAccessControlControllerCreateRoleV1MutationOptions = <
  TError = void | void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof accessControlControllerCreateRoleV1>>,
    TError,
    { orgId: string; data: CreateRoleDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof accessControlControllerCreateRoleV1>>,
  TError,
  { orgId: string; data: CreateRoleDto },
  TContext
> => {
  const mutationKey = ['accessControlControllerCreateRoleV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof accessControlControllerCreateRoleV1>>,
    { orgId: string; data: CreateRoleDto }
  > = (props) => {
    const { orgId, data } = props ?? {};

    return accessControlControllerCreateRoleV1(orgId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AccessControlControllerCreateRoleV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof accessControlControllerCreateRoleV1>>
>;
export type AccessControlControllerCreateRoleV1MutationBody = CreateRoleDto;
export type AccessControlControllerCreateRoleV1MutationError =
  | void
  | void
  | void;

/**
 * @summary Create a new role for an organization
 */
export const useAccessControlControllerCreateRoleV1 = <
  TError = void | void | void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof accessControlControllerCreateRoleV1>>,
      TError,
      { orgId: string; data: CreateRoleDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof accessControlControllerCreateRoleV1>>,
  TError,
  { orgId: string; data: CreateRoleDto },
  TContext
> => {
  const mutationOptions =
    getAccessControlControllerCreateRoleV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Updates a role's name and/or permissions. Updating permissions deletes old associations and creates new ones. Operation is transactional.
 * @summary Update a role
 */
export const accessControlControllerUpdateRoleV1 = (
  orgId: string,
  roleId: string,
  updateRoleDto: UpdateRoleDto,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<AccessControlControllerUpdateRoleV1200>(
    {
      url: `/api/v1/organizations/${orgId}/roles/${roleId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateRoleDto,
    },
    options
  );
};

export const getAccessControlControllerUpdateRoleV1MutationOptions = <
  TError = void | void | void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof accessControlControllerUpdateRoleV1>>,
    TError,
    { orgId: string; roleId: string; data: UpdateRoleDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof accessControlControllerUpdateRoleV1>>,
  TError,
  { orgId: string; roleId: string; data: UpdateRoleDto },
  TContext
> => {
  const mutationKey = ['accessControlControllerUpdateRoleV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof accessControlControllerUpdateRoleV1>>,
    { orgId: string; roleId: string; data: UpdateRoleDto }
  > = (props) => {
    const { orgId, roleId, data } = props ?? {};

    return accessControlControllerUpdateRoleV1(
      orgId,
      roleId,
      data,
      requestOptions
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type AccessControlControllerUpdateRoleV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof accessControlControllerUpdateRoleV1>>
>;
export type AccessControlControllerUpdateRoleV1MutationBody = UpdateRoleDto;
export type AccessControlControllerUpdateRoleV1MutationError =
  | void
  | void
  | void
  | void;

/**
 * @summary Update a role
 */
export const useAccessControlControllerUpdateRoleV1 = <
  TError = void | void | void | void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof accessControlControllerUpdateRoleV1>>,
      TError,
      { orgId: string; roleId: string; data: UpdateRoleDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof accessControlControllerUpdateRoleV1>>,
  TError,
  { orgId: string; roleId: string; data: UpdateRoleDto },
  TContext
> => {
  const mutationOptions =
    getAccessControlControllerUpdateRoleV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Deletes a role. Cannot delete "Owner" or "Admin" protected roles, or roles with active members.
 * @summary Delete a role from an organization
 */
export const accessControlControllerDeleteRoleV1 = (
  orgId: string,
  roleId: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<AccessControlControllerDeleteRoleV1200>(
    { url: `/api/v1/organizations/${orgId}/roles/${roleId}`, method: 'DELETE' },
    options
  );
};

export const getAccessControlControllerDeleteRoleV1MutationOptions = <
  TError = void | void | void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof accessControlControllerDeleteRoleV1>>,
    TError,
    { orgId: string; roleId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof accessControlControllerDeleteRoleV1>>,
  TError,
  { orgId: string; roleId: string },
  TContext
> => {
  const mutationKey = ['accessControlControllerDeleteRoleV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof accessControlControllerDeleteRoleV1>>,
    { orgId: string; roleId: string }
  > = (props) => {
    const { orgId, roleId } = props ?? {};

    return accessControlControllerDeleteRoleV1(orgId, roleId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AccessControlControllerDeleteRoleV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof accessControlControllerDeleteRoleV1>>
>;

export type AccessControlControllerDeleteRoleV1MutationError =
  | void
  | void
  | void
  | void;

/**
 * @summary Delete a role from an organization
 */
export const useAccessControlControllerDeleteRoleV1 = <
  TError = void | void | void | void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof accessControlControllerDeleteRoleV1>>,
      TError,
      { orgId: string; roleId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof accessControlControllerDeleteRoleV1>>,
  TError,
  { orgId: string; roleId: string },
  TContext
> => {
  const mutationOptions =
    getAccessControlControllerDeleteRoleV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Allows the organization Owner to change another member's role. Cannot change the role of the Owner.
 * @summary Change a member's role
 */
export const accessControlControllerChangeMemberRoleV1 = (
  orgId: string,
  membershipId: string,
  updateMemberRoleDto: UpdateMemberRoleDto,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<AccessControlControllerChangeMemberRoleV1200>(
    {
      url: `/api/v1/organizations/${orgId}/roles/memberships/${membershipId}/role`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateMemberRoleDto,
    },
    options
  );
};

export const getAccessControlControllerChangeMemberRoleV1MutationOptions = <
  TError = void | void | void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof accessControlControllerChangeMemberRoleV1>>,
    TError,
    { orgId: string; membershipId: string; data: UpdateMemberRoleDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof accessControlControllerChangeMemberRoleV1>>,
  TError,
  { orgId: string; membershipId: string; data: UpdateMemberRoleDto },
  TContext
> => {
  const mutationKey = ['accessControlControllerChangeMemberRoleV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof accessControlControllerChangeMemberRoleV1>>,
    { orgId: string; membershipId: string; data: UpdateMemberRoleDto }
  > = (props) => {
    const { orgId, membershipId, data } = props ?? {};

    return accessControlControllerChangeMemberRoleV1(
      orgId,
      membershipId,
      data,
      requestOptions
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type AccessControlControllerChangeMemberRoleV1MutationResult =
  NonNullable<
    Awaited<ReturnType<typeof accessControlControllerChangeMemberRoleV1>>
  >;
export type AccessControlControllerChangeMemberRoleV1MutationBody =
  UpdateMemberRoleDto;
export type AccessControlControllerChangeMemberRoleV1MutationError =
  | void
  | void
  | void
  | void;

/**
 * @summary Change a member's role
 */
export const useAccessControlControllerChangeMemberRoleV1 = <
  TError = void | void | void | void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof accessControlControllerChangeMemberRoleV1>>,
      TError,
      { orgId: string; membershipId: string; data: UpdateMemberRoleDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof accessControlControllerChangeMemberRoleV1>>,
  TError,
  { orgId: string; membershipId: string; data: UpdateMemberRoleDto },
  TContext
> => {
  const mutationOptions =
    getAccessControlControllerChangeMemberRoleV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Allows the organization Owner to grant or revoke specific permissions to a member via permission overrides. Cannot override permissions for the Owner.
 * @summary Assign a permission override to a member
 */
export const accessControlControllerAssignPermissionOverrideV1 = (
  orgId: string,
  membershipId: string,
  createPermissionOverrideDto: CreatePermissionOverrideDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<AccessControlControllerAssignPermissionOverrideV1201>(
    {
      url: `/api/v1/organizations/${orgId}/roles/memberships/${membershipId}/overrides`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createPermissionOverrideDto,
      signal,
    },
    options
  );
};

export const getAccessControlControllerAssignPermissionOverrideV1MutationOptions =
  <TError = void | void | void | void, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<typeof accessControlControllerAssignPermissionOverrideV1>
      >,
      TError,
      {
        orgId: string;
        membershipId: string;
        data: CreatePermissionOverrideDto;
      },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  }): UseMutationOptions<
    Awaited<
      ReturnType<typeof accessControlControllerAssignPermissionOverrideV1>
    >,
    TError,
    { orgId: string; membershipId: string; data: CreatePermissionOverrideDto },
    TContext
  > => {
    const mutationKey = ['accessControlControllerAssignPermissionOverrideV1'];
    const { mutation: mutationOptions, request: requestOptions } = options
      ? options.mutation &&
        'mutationKey' in options.mutation &&
        options.mutation.mutationKey
        ? options
        : { ...options, mutation: { ...options.mutation, mutationKey } }
      : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
      Awaited<
        ReturnType<typeof accessControlControllerAssignPermissionOverrideV1>
      >,
      { orgId: string; membershipId: string; data: CreatePermissionOverrideDto }
    > = (props) => {
      const { orgId, membershipId, data } = props ?? {};

      return accessControlControllerAssignPermissionOverrideV1(
        orgId,
        membershipId,
        data,
        requestOptions
      );
    };

    return { mutationFn, ...mutationOptions };
  };

export type AccessControlControllerAssignPermissionOverrideV1MutationResult =
  NonNullable<
    Awaited<
      ReturnType<typeof accessControlControllerAssignPermissionOverrideV1>
    >
  >;
export type AccessControlControllerAssignPermissionOverrideV1MutationBody =
  CreatePermissionOverrideDto;
export type AccessControlControllerAssignPermissionOverrideV1MutationError =
  | void
  | void
  | void
  | void;

/**
 * @summary Assign a permission override to a member
 */
export const useAccessControlControllerAssignPermissionOverrideV1 = <
  TError = void | void | void | void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<typeof accessControlControllerAssignPermissionOverrideV1>
      >,
      TError,
      {
        orgId: string;
        membershipId: string;
        data: CreatePermissionOverrideDto;
      },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof accessControlControllerAssignPermissionOverrideV1>>,
  TError,
  { orgId: string; membershipId: string; data: CreatePermissionOverrideDto },
  TContext
> => {
  const mutationOptions =
    getAccessControlControllerAssignPermissionOverrideV1MutationOptions(
      options
    );

  return useMutation(mutationOptions, queryClient);
};
/**
 * Retrieves a detailed breakdown of a member's permissions, distinguishing between role-inherited permissions and explicit permission overrides.
 * @summary Get a member's permission breakdown
 */
export const accessControlControllerGetMemberPermissionBreakdownV1 = (
  orgId: string,
  membershipId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<AccessControlControllerGetMemberPermissionBreakdownV1200>(
    {
      url: `/api/v1/organizations/${orgId}/roles/memberships/${membershipId}/permissions-breakdown`,
      method: 'GET',
      signal,
    },
    options
  );
};

export const getAccessControlControllerGetMemberPermissionBreakdownV1QueryKey =
  (orgId?: string, membershipId?: string) => {
    return [
      `/api/v1/organizations/${orgId}/roles/memberships/${membershipId}/permissions-breakdown`,
    ] as const;
  };

export const getAccessControlControllerGetMemberPermissionBreakdownV1QueryOptions =
  <
    TData = Awaited<
      ReturnType<typeof accessControlControllerGetMemberPermissionBreakdownV1>
    >,
    TError = void | void | void,
  >(
    orgId: string,
    membershipId: string,
    options?: {
      query?: Partial<
        UseQueryOptions<
          Awaited<
            ReturnType<
              typeof accessControlControllerGetMemberPermissionBreakdownV1
            >
          >,
          TError,
          TData
        >
      >;
      request?: SecondParameter<typeof customInstance>;
    }
  ) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
      queryOptions?.queryKey ??
      getAccessControlControllerGetMemberPermissionBreakdownV1QueryKey(
        orgId,
        membershipId
      );

    const queryFn: QueryFunction<
      Awaited<
        ReturnType<typeof accessControlControllerGetMemberPermissionBreakdownV1>
      >
    > = ({ signal }) =>
      accessControlControllerGetMemberPermissionBreakdownV1(
        orgId,
        membershipId,
        requestOptions,
        signal
      );

    return {
      queryKey,
      queryFn,
      enabled: !!(orgId && membershipId),
      ...queryOptions,
    } as UseQueryOptions<
      Awaited<
        ReturnType<typeof accessControlControllerGetMemberPermissionBreakdownV1>
      >,
      TError,
      TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
  };

export type AccessControlControllerGetMemberPermissionBreakdownV1QueryResult =
  NonNullable<
    Awaited<
      ReturnType<typeof accessControlControllerGetMemberPermissionBreakdownV1>
    >
  >;
export type AccessControlControllerGetMemberPermissionBreakdownV1QueryError =
  | void
  | void
  | void;

export function useAccessControlControllerGetMemberPermissionBreakdownV1<
  TData = Awaited<
    ReturnType<typeof accessControlControllerGetMemberPermissionBreakdownV1>
  >,
  TError = void | void | void,
>(
  orgId: string,
  membershipId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof accessControlControllerGetMemberPermissionBreakdownV1
          >
        >,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<
              typeof accessControlControllerGetMemberPermissionBreakdownV1
            >
          >,
          TError,
          Awaited<
            ReturnType<
              typeof accessControlControllerGetMemberPermissionBreakdownV1
            >
          >
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAccessControlControllerGetMemberPermissionBreakdownV1<
  TData = Awaited<
    ReturnType<typeof accessControlControllerGetMemberPermissionBreakdownV1>
  >,
  TError = void | void | void,
>(
  orgId: string,
  membershipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof accessControlControllerGetMemberPermissionBreakdownV1
          >
        >,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<
              typeof accessControlControllerGetMemberPermissionBreakdownV1
            >
          >,
          TError,
          Awaited<
            ReturnType<
              typeof accessControlControllerGetMemberPermissionBreakdownV1
            >
          >
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAccessControlControllerGetMemberPermissionBreakdownV1<
  TData = Awaited<
    ReturnType<typeof accessControlControllerGetMemberPermissionBreakdownV1>
  >,
  TError = void | void | void,
>(
  orgId: string,
  membershipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof accessControlControllerGetMemberPermissionBreakdownV1
          >
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a member's permission breakdown
 */

export function useAccessControlControllerGetMemberPermissionBreakdownV1<
  TData = Awaited<
    ReturnType<typeof accessControlControllerGetMemberPermissionBreakdownV1>
  >,
  TError = void | void | void,
>(
  orgId: string,
  membershipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof accessControlControllerGetMemberPermissionBreakdownV1
          >
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getAccessControlControllerGetMemberPermissionBreakdownV1QueryOptions(
      orgId,
      membershipId,
      options
    );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
