/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { CreateSocialLinkDto, UpdateSocialLinkDto } from '../model';

import { customInstance } from '../../lib/api-custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Create a social link
 */
export const socialLinksControllerCreateV1 = (
  createSocialLinkDto: CreateSocialLinkDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/v1/social-links`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createSocialLinkDto,
      signal,
    },
    options
  );
};

export const getSocialLinksControllerCreateV1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof socialLinksControllerCreateV1>>,
    TError,
    { data: CreateSocialLinkDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof socialLinksControllerCreateV1>>,
  TError,
  { data: CreateSocialLinkDto },
  TContext
> => {
  const mutationKey = ['socialLinksControllerCreateV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof socialLinksControllerCreateV1>>,
    { data: CreateSocialLinkDto }
  > = (props) => {
    const { data } = props ?? {};

    return socialLinksControllerCreateV1(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SocialLinksControllerCreateV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof socialLinksControllerCreateV1>>
>;
export type SocialLinksControllerCreateV1MutationBody = CreateSocialLinkDto;
export type SocialLinksControllerCreateV1MutationError = unknown;

/**
 * @summary Create a social link
 */
export const useSocialLinksControllerCreateV1 = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof socialLinksControllerCreateV1>>,
      TError,
      { data: CreateSocialLinkDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof socialLinksControllerCreateV1>>,
  TError,
  { data: CreateSocialLinkDto },
  TContext
> => {
  const mutationOptions =
    getSocialLinksControllerCreateV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary List social links for the organization
 */
export const socialLinksControllerFindAllV1 = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    { url: `/api/v1/social-links`, method: 'GET', signal },
    options
  );
};

export const getSocialLinksControllerFindAllV1QueryKey = () => {
  return [`/api/v1/social-links`] as const;
};

export const getSocialLinksControllerFindAllV1QueryOptions = <
  TData = Awaited<ReturnType<typeof socialLinksControllerFindAllV1>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof socialLinksControllerFindAllV1>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSocialLinksControllerFindAllV1QueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof socialLinksControllerFindAllV1>>
  > = ({ signal }) => socialLinksControllerFindAllV1(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof socialLinksControllerFindAllV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SocialLinksControllerFindAllV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof socialLinksControllerFindAllV1>>
>;
export type SocialLinksControllerFindAllV1QueryError = unknown;

export function useSocialLinksControllerFindAllV1<
  TData = Awaited<ReturnType<typeof socialLinksControllerFindAllV1>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof socialLinksControllerFindAllV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof socialLinksControllerFindAllV1>>,
          TError,
          Awaited<ReturnType<typeof socialLinksControllerFindAllV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSocialLinksControllerFindAllV1<
  TData = Awaited<ReturnType<typeof socialLinksControllerFindAllV1>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof socialLinksControllerFindAllV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof socialLinksControllerFindAllV1>>,
          TError,
          Awaited<ReturnType<typeof socialLinksControllerFindAllV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSocialLinksControllerFindAllV1<
  TData = Awaited<ReturnType<typeof socialLinksControllerFindAllV1>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof socialLinksControllerFindAllV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List social links for the organization
 */

export function useSocialLinksControllerFindAllV1<
  TData = Awaited<ReturnType<typeof socialLinksControllerFindAllV1>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof socialLinksControllerFindAllV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSocialLinksControllerFindAllV1QueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update a social link
 */
export const socialLinksControllerUpdateV1 = (
  id: string,
  updateSocialLinkDto: UpdateSocialLinkDto,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    {
      url: `/api/v1/social-links/${id}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateSocialLinkDto,
    },
    options
  );
};

export const getSocialLinksControllerUpdateV1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof socialLinksControllerUpdateV1>>,
    TError,
    { id: string; data: UpdateSocialLinkDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof socialLinksControllerUpdateV1>>,
  TError,
  { id: string; data: UpdateSocialLinkDto },
  TContext
> => {
  const mutationKey = ['socialLinksControllerUpdateV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof socialLinksControllerUpdateV1>>,
    { id: string; data: UpdateSocialLinkDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return socialLinksControllerUpdateV1(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SocialLinksControllerUpdateV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof socialLinksControllerUpdateV1>>
>;
export type SocialLinksControllerUpdateV1MutationBody = UpdateSocialLinkDto;
export type SocialLinksControllerUpdateV1MutationError = unknown;

/**
 * @summary Update a social link
 */
export const useSocialLinksControllerUpdateV1 = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof socialLinksControllerUpdateV1>>,
      TError,
      { id: string; data: UpdateSocialLinkDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof socialLinksControllerUpdateV1>>,
  TError,
  { id: string; data: UpdateSocialLinkDto },
  TContext
> => {
  const mutationOptions =
    getSocialLinksControllerUpdateV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Delete a social link
 */
export const socialLinksControllerRemoveV1 = (
  id: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    { url: `/api/v1/social-links/${id}`, method: 'DELETE' },
    options
  );
};

export const getSocialLinksControllerRemoveV1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof socialLinksControllerRemoveV1>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof socialLinksControllerRemoveV1>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['socialLinksControllerRemoveV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof socialLinksControllerRemoveV1>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return socialLinksControllerRemoveV1(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SocialLinksControllerRemoveV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof socialLinksControllerRemoveV1>>
>;

export type SocialLinksControllerRemoveV1MutationError = unknown;

/**
 * @summary Delete a social link
 */
export const useSocialLinksControllerRemoveV1 = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof socialLinksControllerRemoveV1>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof socialLinksControllerRemoveV1>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions =
    getSocialLinksControllerRemoveV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
