/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  UpdateMemberProfileDto,
  UpdateUserProfileDto,
  UsersControllerAcceptInviteV1200,
  UsersControllerGetCurrentUserV1200,
  UsersControllerGetPerformanceProfileV1200,
  UsersControllerGetPermissionsV1200,
  UsersControllerGetUserOrganizationsV1200Item,
} from '../model';

import { customInstance } from '../../lib/api-custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Returns the authenticated user's profile information. Include x-organization-id header to get permissions for that organization.
 * @summary Get current user profile with optional permissions
 */
export const usersControllerGetCurrentUserV1 = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<UsersControllerGetCurrentUserV1200>(
    { url: `/api/v1/users/me`, method: 'GET', signal },
    options
  );
};

export const getUsersControllerGetCurrentUserV1QueryKey = () => {
  return [`/api/v1/users/me`] as const;
};

export const getUsersControllerGetCurrentUserV1QueryOptions = <
  TData = Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>,
  TError = void | void,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getUsersControllerGetCurrentUserV1QueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>
  > = ({ signal }) => usersControllerGetCurrentUserV1(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UsersControllerGetCurrentUserV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>
>;
export type UsersControllerGetCurrentUserV1QueryError = void | void;

export function useUsersControllerGetCurrentUserV1<
  TData = Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>,
  TError = void | void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUsersControllerGetCurrentUserV1<
  TData = Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>,
  TError = void | void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUsersControllerGetCurrentUserV1<
  TData = Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>,
  TError = void | void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get current user profile with optional permissions
 */

export function useUsersControllerGetCurrentUserV1<
  TData = Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>,
  TError = void | void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getUsersControllerGetCurrentUserV1QueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Updates user profile information that applies across all organizations (avatar, phone, languages, etc.)
 * @summary Update global user profile
 */
export const usersControllerUpdateGlobalProfileV1 = (
  updateUserProfileDto: UpdateUserProfileDto,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    {
      url: `/api/v1/users/me`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateUserProfileDto,
    },
    options
  );
};

export const getUsersControllerUpdateGlobalProfileV1MutationOptions = <
  TError = void | void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerUpdateGlobalProfileV1>>,
    TError,
    { data: UpdateUserProfileDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerUpdateGlobalProfileV1>>,
  TError,
  { data: UpdateUserProfileDto },
  TContext
> => {
  const mutationKey = ['usersControllerUpdateGlobalProfileV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerUpdateGlobalProfileV1>>,
    { data: UpdateUserProfileDto }
  > = (props) => {
    const { data } = props ?? {};

    return usersControllerUpdateGlobalProfileV1(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UsersControllerUpdateGlobalProfileV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerUpdateGlobalProfileV1>>
>;
export type UsersControllerUpdateGlobalProfileV1MutationBody =
  UpdateUserProfileDto;
export type UsersControllerUpdateGlobalProfileV1MutationError =
  | void
  | void
  | void;

/**
 * @summary Update global user profile
 */
export const useUsersControllerUpdateGlobalProfileV1 = <
  TError = void | void | void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof usersControllerUpdateGlobalProfileV1>>,
      TError,
      { data: UpdateUserProfileDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerUpdateGlobalProfileV1>>,
  TError,
  { data: UpdateUserProfileDto },
  TContext
> => {
  const mutationOptions =
    getUsersControllerUpdateGlobalProfileV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Returns the effective permissions for the authenticated user in their active organization context. Requires x-organization-id header.
 * @summary Get user permissions for organization
 */
export const usersControllerGetPermissionsV1 = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<UsersControllerGetPermissionsV1200>(
    { url: `/api/v1/users/me/permissions`, method: 'GET', signal },
    options
  );
};

export const getUsersControllerGetPermissionsV1QueryKey = () => {
  return [`/api/v1/users/me/permissions`] as const;
};

export const getUsersControllerGetPermissionsV1QueryOptions = <
  TData = Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>,
  TError = void | void,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getUsersControllerGetPermissionsV1QueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>
  > = ({ signal }) => usersControllerGetPermissionsV1(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UsersControllerGetPermissionsV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>
>;
export type UsersControllerGetPermissionsV1QueryError = void | void;

export function useUsersControllerGetPermissionsV1<
  TData = Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>,
  TError = void | void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUsersControllerGetPermissionsV1<
  TData = Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>,
  TError = void | void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUsersControllerGetPermissionsV1<
  TData = Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>,
  TError = void | void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get user permissions for organization
 */

export function useUsersControllerGetPermissionsV1<
  TData = Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>,
  TError = void | void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getUsersControllerGetPermissionsV1QueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Returns all organizations the user belongs to, used for workspace switching
 * @summary Get user's organizations
 */
export const usersControllerGetUserOrganizationsV1 = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<UsersControllerGetUserOrganizationsV1200Item[]>(
    { url: `/api/v1/users/me/organizations`, method: 'GET', signal },
    options
  );
};

export const getUsersControllerGetUserOrganizationsV1QueryKey = () => {
  return [`/api/v1/users/me/organizations`] as const;
};

export const getUsersControllerGetUserOrganizationsV1QueryOptions = <
  TData = Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getUsersControllerGetUserOrganizationsV1QueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>
  > = ({ signal }) =>
    usersControllerGetUserOrganizationsV1(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UsersControllerGetUserOrganizationsV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>
>;
export type UsersControllerGetUserOrganizationsV1QueryError = void;

export function useUsersControllerGetUserOrganizationsV1<
  TData = Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUsersControllerGetUserOrganizationsV1<
  TData = Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUsersControllerGetUserOrganizationsV1<
  TData = Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get user's organizations
 */

export function useUsersControllerGetUserOrganizationsV1<
  TData = Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getUsersControllerGetUserOrganizationsV1QueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Accepts a pending invite and activates the membership. Only works on invites with status "invited".
 * @summary Accept an organization invite
 */
export const usersControllerAcceptInviteV1 = (
  inviteId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<UsersControllerAcceptInviteV1200>(
    { url: `/api/v1/users/invites/${inviteId}/accept`, method: 'POST', signal },
    options
  );
};

export const getUsersControllerAcceptInviteV1MutationOptions = <
  TError = void | void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerAcceptInviteV1>>,
    TError,
    { inviteId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerAcceptInviteV1>>,
  TError,
  { inviteId: string },
  TContext
> => {
  const mutationKey = ['usersControllerAcceptInviteV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerAcceptInviteV1>>,
    { inviteId: string }
  > = (props) => {
    const { inviteId } = props ?? {};

    return usersControllerAcceptInviteV1(inviteId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UsersControllerAcceptInviteV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerAcceptInviteV1>>
>;

export type UsersControllerAcceptInviteV1MutationError = void | void | void;

/**
 * @summary Accept an organization invite
 */
export const useUsersControllerAcceptInviteV1 = <
  TError = void | void | void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof usersControllerAcceptInviteV1>>,
      TError,
      { inviteId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerAcceptInviteV1>>,
  TError,
  { inviteId: string },
  TContext
> => {
  const mutationOptions =
    getUsersControllerAcceptInviteV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Deletes a pending join request that belongs to the authenticated user.
 * @summary Cancel current user pending join request
 */
export const usersControllerCancelJoinRequestV1 = (
  id: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    { url: `/api/v1/users/me/requests/${id}/cancel`, method: 'DELETE' },
    options
  );
};

export const getUsersControllerCancelJoinRequestV1MutationOptions = <
  TError = void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerCancelJoinRequestV1>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerCancelJoinRequestV1>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['usersControllerCancelJoinRequestV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerCancelJoinRequestV1>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return usersControllerCancelJoinRequestV1(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UsersControllerCancelJoinRequestV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerCancelJoinRequestV1>>
>;

export type UsersControllerCancelJoinRequestV1MutationError = void | void;

/**
 * @summary Cancel current user pending join request
 */
export const useUsersControllerCancelJoinRequestV1 = <
  TError = void | void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof usersControllerCancelJoinRequestV1>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerCancelJoinRequestV1>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions =
    getUsersControllerCancelJoinRequestV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Retrieves combined user profile, membership info, and calculated sales metrics (MTD revenue)
 * @summary Get performance dashboard profile
 */
export const usersControllerGetPerformanceProfileV1 = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<UsersControllerGetPerformanceProfileV1200>(
    { url: `/api/v1/users/performance-profile`, method: 'GET', signal },
    options
  );
};

export const getUsersControllerGetPerformanceProfileV1QueryKey = () => {
  return [`/api/v1/users/performance-profile`] as const;
};

export const getUsersControllerGetPerformanceProfileV1QueryOptions = <
  TData = Awaited<ReturnType<typeof usersControllerGetPerformanceProfileV1>>,
  TError = void | void,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof usersControllerGetPerformanceProfileV1>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getUsersControllerGetPerformanceProfileV1QueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof usersControllerGetPerformanceProfileV1>>
  > = ({ signal }) =>
    usersControllerGetPerformanceProfileV1(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerGetPerformanceProfileV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UsersControllerGetPerformanceProfileV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerGetPerformanceProfileV1>>
>;
export type UsersControllerGetPerformanceProfileV1QueryError = void | void;

export function useUsersControllerGetPerformanceProfileV1<
  TData = Awaited<ReturnType<typeof usersControllerGetPerformanceProfileV1>>,
  TError = void | void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetPerformanceProfileV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetPerformanceProfileV1>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetPerformanceProfileV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUsersControllerGetPerformanceProfileV1<
  TData = Awaited<ReturnType<typeof usersControllerGetPerformanceProfileV1>>,
  TError = void | void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetPerformanceProfileV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetPerformanceProfileV1>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetPerformanceProfileV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUsersControllerGetPerformanceProfileV1<
  TData = Awaited<ReturnType<typeof usersControllerGetPerformanceProfileV1>>,
  TError = void | void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetPerformanceProfileV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get performance dashboard profile
 */

export function useUsersControllerGetPerformanceProfileV1<
  TData = Awaited<ReturnType<typeof usersControllerGetPerformanceProfileV1>>,
  TError = void | void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetPerformanceProfileV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getUsersControllerGetPerformanceProfileV1QueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Updates organization-specific profile information (job title, tier, specializations, availability, etc.)
 * @summary Update membership profile
 */
export const usersControllerUpdateMembershipProfileV1 = (
  updateMemberProfileDto: UpdateMemberProfileDto,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    {
      url: `/api/v1/users/me/membership`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateMemberProfileDto,
    },
    options
  );
};

export const getUsersControllerUpdateMembershipProfileV1MutationOptions = <
  TError = void | void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerUpdateMembershipProfileV1>>,
    TError,
    { data: UpdateMemberProfileDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerUpdateMembershipProfileV1>>,
  TError,
  { data: UpdateMemberProfileDto },
  TContext
> => {
  const mutationKey = ['usersControllerUpdateMembershipProfileV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerUpdateMembershipProfileV1>>,
    { data: UpdateMemberProfileDto }
  > = (props) => {
    const { data } = props ?? {};

    return usersControllerUpdateMembershipProfileV1(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UsersControllerUpdateMembershipProfileV1MutationResult =
  NonNullable<
    Awaited<ReturnType<typeof usersControllerUpdateMembershipProfileV1>>
  >;
export type UsersControllerUpdateMembershipProfileV1MutationBody =
  UpdateMemberProfileDto;
export type UsersControllerUpdateMembershipProfileV1MutationError =
  | void
  | void
  | void;

/**
 * @summary Update membership profile
 */
export const useUsersControllerUpdateMembershipProfileV1 = <
  TError = void | void | void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof usersControllerUpdateMembershipProfileV1>>,
      TError,
      { data: UpdateMemberProfileDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerUpdateMembershipProfileV1>>,
  TError,
  { data: UpdateMemberProfileDto },
  TContext
> => {
  const mutationOptions =
    getUsersControllerUpdateMembershipProfileV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
