/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SaaS API
 * The core API for my multi-tenant SaaS
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  UsersControllerAcceptInviteV1200,
  UsersControllerGetCurrentUserV1200,
  UsersControllerGetPermissionsV1200,
  UsersControllerGetUserOrganizationsV1200Item,
} from '../model';

import { customInstance } from '../../lib/api-custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Returns the authenticated user's profile information. Include x-organization-id header to get permissions for that organization.
 * @summary Get current user profile with optional permissions
 */
export const usersControllerGetCurrentUserV1 = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<UsersControllerGetCurrentUserV1200>(
    { url: `/api/v1/users/me`, method: 'GET', signal },
    options
  );
};

export const getUsersControllerGetCurrentUserV1QueryKey = () => {
  return [`/api/v1/users/me`] as const;
};

export const getUsersControllerGetCurrentUserV1QueryOptions = <
  TData = Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>,
  TError = void | void,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getUsersControllerGetCurrentUserV1QueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>
  > = ({ signal }) => usersControllerGetCurrentUserV1(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UsersControllerGetCurrentUserV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>
>;
export type UsersControllerGetCurrentUserV1QueryError = void | void;

export function useUsersControllerGetCurrentUserV1<
  TData = Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>,
  TError = void | void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUsersControllerGetCurrentUserV1<
  TData = Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>,
  TError = void | void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUsersControllerGetCurrentUserV1<
  TData = Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>,
  TError = void | void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get current user profile with optional permissions
 */

export function useUsersControllerGetCurrentUserV1<
  TData = Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>,
  TError = void | void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetCurrentUserV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getUsersControllerGetCurrentUserV1QueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Returns the effective permissions for the authenticated user in their active organization context. Requires x-organization-id header.
 * @summary Get user permissions for organization
 */
export const usersControllerGetPermissionsV1 = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<UsersControllerGetPermissionsV1200>(
    { url: `/api/v1/users/me/permissions`, method: 'GET', signal },
    options
  );
};

export const getUsersControllerGetPermissionsV1QueryKey = () => {
  return [`/api/v1/users/me/permissions`] as const;
};

export const getUsersControllerGetPermissionsV1QueryOptions = <
  TData = Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>,
  TError = void | void,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getUsersControllerGetPermissionsV1QueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>
  > = ({ signal }) => usersControllerGetPermissionsV1(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UsersControllerGetPermissionsV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>
>;
export type UsersControllerGetPermissionsV1QueryError = void | void;

export function useUsersControllerGetPermissionsV1<
  TData = Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>,
  TError = void | void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUsersControllerGetPermissionsV1<
  TData = Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>,
  TError = void | void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUsersControllerGetPermissionsV1<
  TData = Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>,
  TError = void | void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get user permissions for organization
 */

export function useUsersControllerGetPermissionsV1<
  TData = Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>,
  TError = void | void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetPermissionsV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getUsersControllerGetPermissionsV1QueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Returns all organizations the user belongs to, used for workspace switching
 * @summary Get user's organizations
 */
export const usersControllerGetUserOrganizationsV1 = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<UsersControllerGetUserOrganizationsV1200Item[]>(
    { url: `/api/v1/users/me/organizations`, method: 'GET', signal },
    options
  );
};

export const getUsersControllerGetUserOrganizationsV1QueryKey = () => {
  return [`/api/v1/users/me/organizations`] as const;
};

export const getUsersControllerGetUserOrganizationsV1QueryOptions = <
  TData = Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getUsersControllerGetUserOrganizationsV1QueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>
  > = ({ signal }) =>
    usersControllerGetUserOrganizationsV1(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UsersControllerGetUserOrganizationsV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>
>;
export type UsersControllerGetUserOrganizationsV1QueryError = void;

export function useUsersControllerGetUserOrganizationsV1<
  TData = Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUsersControllerGetUserOrganizationsV1<
  TData = Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUsersControllerGetUserOrganizationsV1<
  TData = Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get user's organizations
 */

export function useUsersControllerGetUserOrganizationsV1<
  TData = Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetUserOrganizationsV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getUsersControllerGetUserOrganizationsV1QueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Accepts a pending invite and activates the membership. Only works on invites with status "invited".
 * @summary Accept an organization invite
 */
export const usersControllerAcceptInviteV1 = (
  inviteId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<UsersControllerAcceptInviteV1200>(
    { url: `/api/v1/users/invites/${inviteId}/accept`, method: 'POST', signal },
    options
  );
};

export const getUsersControllerAcceptInviteV1MutationOptions = <
  TError = void | void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerAcceptInviteV1>>,
    TError,
    { inviteId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerAcceptInviteV1>>,
  TError,
  { inviteId: string },
  TContext
> => {
  const mutationKey = ['usersControllerAcceptInviteV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerAcceptInviteV1>>,
    { inviteId: string }
  > = (props) => {
    const { inviteId } = props ?? {};

    return usersControllerAcceptInviteV1(inviteId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UsersControllerAcceptInviteV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerAcceptInviteV1>>
>;

export type UsersControllerAcceptInviteV1MutationError = void | void | void;

/**
 * @summary Accept an organization invite
 */
export const useUsersControllerAcceptInviteV1 = <
  TError = void | void | void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof usersControllerAcceptInviteV1>>,
      TError,
      { inviteId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerAcceptInviteV1>>,
  TError,
  { inviteId: string },
  TContext
> => {
  const mutationOptions =
    getUsersControllerAcceptInviteV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Deletes a pending join request that belongs to the authenticated user.
 * @summary Cancel current user pending join request
 */
export const usersControllerCancelJoinRequestV1 = (
  id: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    { url: `/api/v1/users/me/requests/${id}/cancel`, method: 'DELETE' },
    options
  );
};

export const getUsersControllerCancelJoinRequestV1MutationOptions = <
  TError = void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerCancelJoinRequestV1>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerCancelJoinRequestV1>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['usersControllerCancelJoinRequestV1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerCancelJoinRequestV1>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return usersControllerCancelJoinRequestV1(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UsersControllerCancelJoinRequestV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerCancelJoinRequestV1>>
>;

export type UsersControllerCancelJoinRequestV1MutationError = void | void;

/**
 * @summary Cancel current user pending join request
 */
export const useUsersControllerCancelJoinRequestV1 = <
  TError = void | void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof usersControllerCancelJoinRequestV1>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerCancelJoinRequestV1>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions =
    getUsersControllerCancelJoinRequestV1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
